window.PROGRAMS = [
  {
    id: "cmu-mhci",
    rank: 1,
    region: "US",
    school: "Carnegie Mellon University",
    short: "CMU",
    program: "Master of Human-Computer Interaction (MHCI)",
    length: "1 year",
    tuition: "$72,000",
    location: "Pittsburgh, PA",
    classSize: "60",
    toefl: "100",
    gre: "Optional / varies",
    portfolio: "Optional",
    deadline: "Jan",
    fee: "$100",
    commitment: "Full-time",
    founded: "1997",
    stem: true,
    tags: ["career", "stem"],
    gpa: "No minimum",
    sop: "Required",
    resume: "Required",
    recommendation: "3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful, not required",
    website: "https://www.hcii.cmu.edu/academics/mhci",
    note: "典型的职业导向 HCI 项目，适合希望快速进入 UX Research、Product Design、Design Strategy 或 HCI Product 方向的申请者。"
  },
  {
    id: "uw-mhcid",
    rank: 2,
    region: "US",
    school: "University of Washington",
    short: "UW",
    program: "Master of Human-Computer Interaction and Design (MHCI+D)",
    length: "1 year",
    tuition: "$52,704",
    location: "Seattle, WA",
    classSize: "30",
    toefl: "106",
    gre: "Not required",
    portfolio: "Optional",
    deadline: "Jan",
    fee: "$85",
    commitment: "Full-time",
    founded: "2012",
    stem: true,
    tags: ["career", "stem"],
    gpa: "No minimum",
    sop: "Required",
    resume: "Required",
    recommendation: "3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://mhcid.washington.edu/",
    note: "跨学院项目，Seattle 科技生态强，适合希望把设计、研究、产品和技术结合起来的申请者。"
  },
  {
    id: "uw-hcde",
    rank: 3,
    region: "US",
    school: "University of Washington",
    short: "UW",
    program: "M.S. in Human Centered Design & Engineering (HCDE)",
    length: "2 years",
    tuition: "$41,280",
    location: "Seattle, WA",
    classSize: "120",
    toefl: "106",
    gre: "Not required",
    portfolio: "Not required",
    deadline: "Jan",
    fee: "$85",
    commitment: "Full-time / Part-time",
    founded: "1980s",
    stem: true,
    tags: ["research", "stem"],
    gpa: "No minimum",
    sop: "Required",
    resume: "Required",
    recommendation: "3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://www.hcde.washington.edu/ms",
    note: "更偏工程、人因、研究与系统化设计，适合有研究意识、技术兴趣或希望申请 PhD 的学生。"
  },
  {
    id: "gatech-ms-hci",
    rank: 4,
    region: "US",
    school: "Georgia Tech",
    short: "GT",
    program: "Master of Science in Human-Computer Interaction",
    length: "2 years",
    tuition: "$70,816",
    location: "Atlanta, GA",
    classSize: "52",
    toefl: "100",
    gre: "Optional / varies",
    portfolio: "Optional",
    deadline: "Feb",
    fee: "$95",
    commitment: "Full-time",
    founded: "1997",
    stem: true,
    tags: ["research", "stem"],
    gpa: "No minimum",
    sop: "Required",
    resume: "Required",
    recommendation: "3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://mshci.gatech.edu/",
    note: "HCI 老牌项目，计算、设计、心理学等方向资源丰富，适合想做更扎实 HCI 研究或产品研究的申请者。"
  },
  {
    id: "umich-msi-ux",
    rank: 5,
    region: "US",
    school: "University of Michigan",
    short: "UM",
    program: "Master of Science in Information - UX Research and Design",
    length: "2 years",
    tuition: "$56,000",
    location: "Ann Arbor, MI",
    classSize: "Large",
    toefl: "100",
    gre: "Not required",
    portfolio: "Optional",
    deadline: "Jan",
    fee: "$75",
    commitment: "Full-time",
    founded: "1996",
    stem: true,
    tags: ["career", "research", "stem"],
    gpa: "No minimum",
    sop: "Required",
    resume: "Required",
    recommendation: "2-3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://www.si.umich.edu/programs/master-science-information",
    note: "信息学院体系，UX、数据、社会计算资源都强，适合背景多元、希望保留多种就业路径的申请者。"
  },
  {
    id: "iupui-hci",
    rank: 6,
    region: "US",
    school: "Indiana University Indianapolis",
    short: "IU",
    program: "M.S. in Human-Computer Interaction",
    length: "2 years",
    tuition: "$44,000",
    location: "Indianapolis, IN",
    classSize: "Medium",
    toefl: "79",
    gre: "Not required",
    portfolio: "Recommended",
    deadline: "Jan / Mar",
    fee: "$70",
    commitment: "Full-time",
    founded: "2003",
    stem: true,
    tags: ["career", "stem"],
    gpa: "3.0 recommended",
    sop: "Required",
    resume: "Required",
    recommendation: "3 letters",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://luddy.indianapolis.iu.edu/academics/graduate-programs/hci-ms/",
    note: "对转专业申请者相对友好，适合希望通过作品集和项目经历建立 UX 转型叙事的人。"
  },
  {
    id: "ucl-hci",
    rank: 7,
    region: "Non-US",
    school: "University College London",
    short: "UCL",
    program: "MSc Human-Computer Interaction",
    length: "1 year",
    tuition: "£35,000+",
    location: "London, UK",
    classSize: "Medium",
    toefl: "Accepted",
    gre: "Not required",
    portfolio: "Not required",
    deadline: "Rolling",
    fee: "Varies",
    commitment: "Full-time",
    founded: "1990s",
    stem: false,
    tags: ["research"],
    gpa: "2:1 equivalent",
    sop: "Required",
    resume: "Required",
    recommendation: "Required",
    ielts: "Required / accepted",
    gmat: "Not required",
    coding: "Helpful",
    website: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/human-computer-interaction-msc",
    note: "英国 HCI 代表项目之一，适合希望一年制完成硕士、重视研究基础和伦敦资源的申请者。"
  },
  {
    id: "kth-ict-innovation",
    rank: 8,
    region: "Non-US",
    school: "KTH Royal Institute of Technology",
    short: "KTH",
    program: "MSc Interactive Media Technology",
    length: "2 years",
    tuition: "SEK 310,000",
    location: "Stockholm, Sweden",
    classSize: "Medium",
    toefl: "Accepted",
    gre: "Not required",
    portfolio: "Varies",
    deadline: "Jan",
    fee: "SEK 900",
    commitment: "Full-time",
    founded: "N/A",
    stem: false,
    tags: ["research"],
    gpa: "Country-specific",
    sop: "Required",
    resume: "Required",
    recommendation: "Varies",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Recommended",
    website: "https://www.kth.se/en/studies/master/interactive-media-technology",
    note: "偏技术与交互媒体，适合希望在欧洲发展、具备一定技术兴趣的学生。"
  },
  {
    id: "hku-dt",
    rank: 9,
    region: "Non-US",
    school: "The University of Hong Kong",
    short: "HKU",
    program: "MSc in Creative Communications / Design-adjacent options",
    length: "1 year",
    tuition: "HKD varies",
    location: "Hong Kong",
    classSize: "Varies",
    toefl: "Accepted",
    gre: "Not required",
    portfolio: "Varies",
    deadline: "Rolling",
    fee: "HKD 300+",
    commitment: "Full-time",
    founded: "N/A",
    stem: false,
    tags: ["career"],
    gpa: "Second class honours",
    sop: "Required",
    resume: "Required",
    recommendation: "Required",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Not required",
    website: "https://admissions.hku.hk/",
    note: "香港方向适合重视地理位置、就业便利和一年制项目的申请者。具体 HCI 匹配度需要按项目细查。"
  },
  {
    id: "nus-is",
    rank: 10,
    region: "Non-US",
    school: "National University of Singapore",
    short: "NUS",
    program: "MComp / Digital and Product-adjacent pathways",
    length: "1-2 years",
    tuition: "SGD varies",
    location: "Singapore",
    classSize: "Varies",
    toefl: "Accepted",
    gre: "Varies",
    portfolio: "Not typical",
    deadline: "Varies",
    fee: "SGD varies",
    commitment: "Full-time",
    founded: "N/A",
    stem: false,
    tags: ["career", "research"],
    gpa: "Strong academic record",
    sop: "Required",
    resume: "Required",
    recommendation: "Required",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Recommended",
    website: "https://www.comp.nus.edu.sg/programmes/pg/",
    note: "新加坡更偏技术与信息系统路径，适合有 CS、数据或产品技术背景的学生。"
  },
  {
    id: "asu-online-ux",
    rank: 11,
    region: "Online",
    school: "Arizona State University",
    short: "ASU",
    program: "Online UX / Graphic Information Technology Pathways",
    length: "Varies",
    tuition: "Varies",
    location: "Online",
    classSize: "Large",
    toefl: "Accepted",
    gre: "Varies",
    portfolio: "Varies",
    deadline: "Multiple",
    fee: "$70",
    commitment: "Online",
    founded: "N/A",
    stem: false,
    tags: ["career"],
    gpa: "Varies",
    sop: "Varies",
    resume: "Varies",
    recommendation: "Varies",
    ielts: "Accepted",
    gmat: "Not required",
    coding: "Not required",
    website: "https://asuonline.asu.edu/",
    note: "在线项目适合在职提升或补充作品集，但如果目标是海外就业和校招资源，需要谨慎评估。"
  }
];
