// Generated by the Top UX Schools content admin. Do not edit this file manually.
window.ARTICLES = [
  {
    "_id": "article-school-list-method",
    "id": "school-list-method",
    "status": "archived",
    "category": "选校",
    "title": "选校表格的终点，是一份能做决定的名单",
    "excerpt": "地区、排名和学费只能帮助你开始搜索。真正有用的名单还要比较项目方法、作品集偏好与自己的不确定性。",
    "readTime": "7 min",
    "date": "2026.06",
    "body": [
      "把项目分成冲刺、匹配和保底并不够。你还需要知道每一所学校究竟在寻找怎样的申请者。",
      "建议为每个项目保留四个判断：项目更偏研究还是实践、你最匹配的经历是什么、最大的风险是什么、下一步需要验证什么。",
      "当一份名单能回答这四个问题，它才真正开始帮助你做决定。"
    ]
  },
  {
    "_id": "article-sop-writing",
    "id": "sop-writing",
    "category": "文书",
    "title": "写了五年HCI文书，这是我给你的文书DIY指南",
    "excerpt": "SOP 不是把简历翻译成段落。它要让招生老师看见：你的职业方向怎样被一段段经历塑造，而这个项目为什么正好是你的下一步。",
    "readTime": "8 min",
    "date": "2026.08",
    "tags": [
      "文书",
      "SOP",
      "DIY",
      "申请方法"
    ],
    "body": [
      "写 SOP 最容易卡在第一句：我到底该从哪一段经历讲起？我的建议是，先别急着写开头。先把它当作一条路线图：它要让招生老师看见你从哪里出发、为什么转向，以及下一步想去哪里。",
      "01｜先把职业目标说清楚",
      "职业目标不需要写成五年规划，也不必急着报出某个具体岗位。只要让人理解你想进入怎样的工作场景：更偏产品、体验、服务、沉浸式媒体，还是教育科技？你现在的经历为什么会把你推到这个方向？",
      "02｜挑 3 到 4 段真正改变过你的经历",
      "不要按年份把简历再讲一遍。优先挑那些让你增加了新能力、改变了判断，或让你第一次真正接触目标领域的经历。它们未必都是最大的项目，但放在一起后，应该能看见一条连续的成长线。",
      "03｜项目匹配要落到你实际研究过的东西",
      "写“贵校排名高、课程丰富”没有信息量。更有用的写法是：你看过哪些课程、工作室、研究方法或行业连接；它们解决了你现阶段的哪个问题；而你已经带着什么经验可以参与进去。",
      "有一个常见误区，是把文书写成一篇观点作文。价值观和兴趣当然可以出现，但读者需要先认识你做过什么、当时怎么判断、后来为什么改变。故事是主体，感悟跟在故事后面，篇幅自然会稳下来。",
      "另一个极端是流水账。每段经历都交代了“我参加了什么”，却没有说明这件事为什么重要。写每个故事前，先补齐五件事：Situation，发生在什么情境；Goal，要解决什么；Action，你具体做了什么；Result，结果或反馈是什么；Takeaway，它改变了你什么。",
      "这套框架不是让你把五个小标题塞进文书。它只是帮你检查：你的叙述里有没有前因后果，有没有自己的行动，有没有一个能把下一段经历接起来的收获。",
      "一篇 1000 词上限的 SOP，通常不需要把字数写满。600 到 800 词足够讲清三四个故事。删掉重复的形容词，把空间留给具体动作、选择和转折，读者会更容易相信这条成长线。",
      "动笔前，可以先写一份故事清单：每段经历只用几行记录当时发生了什么、你做了什么、它改变了你什么。下一步不是润色，而是挑出最能互相支撑的三四段，排出一条你自己读起来也成立的顺序。"
    ],
    "status": "published",
    "images": [
      {
        "fileID": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/sop-writing/1786935236822-0.webp",
        "mini": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/sop-writing/1786935236822-0.webp",
        "web": "assets/articles/cloud/sop-writing/1786935236822-0.webp",
        "alt": "",
        "after": 1
      },
      {
        "fileID": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/sop-writing/1786935247597-0.png",
        "mini": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/sop-writing/1786935247597-0.png",
        "web": "assets/articles/cloud/sop-writing/1786935247597-0.png",
        "alt": "",
        "after": 3
      }
    ]
  },
  {
    "_id": "article-ux-tools",
    "id": "ux-tools",
    "status": "archived",
    "category": "工具",
    "title": "申请季常用工具，先搭一个轻量工作流",
    "excerpt": "项目管理、阅读资料、整理作品集和约访谈对象，各自用一个足够可靠的工具就好。",
    "readTime": "4 min",
    "date": "2026.06",
    "body": [
      "申请是一个持续数月的信息工程，但并不需要复杂的系统。",
      "用表格管理截止日期和要求，用一个文档保存研究与写作素材，用日历固定每周的深度工作时间。工具的目标是让你不再反复找信息。",
      "当你开始觉得工具本身比申请材料更重要时，就该删掉一些了。"
    ]
  },
  {
    "_id": "article-portfolio-topic",
    "id": "portfolio-topic",
    "status": "archived",
    "category": "作品集",
    "title": "作品集选题，不必从一个“大项目”开始",
    "excerpt": "判断选题价值的不是题目听起来多宏大，而是你能否持续地提出问题、做出选择并解释代价。",
    "readTime": "6 min",
    "date": "2026.07",
    "body": [
      "一个好的作品集项目，应该让人看见你如何工作，而不是只看见最后一张漂亮的图。",
      "选题时先问三个问题：我接近这个问题吗？我能得到真实反馈吗？我能在有限时间内完成一次可信的迭代吗？",
      "如果答案是肯定的，小题目也可以做出很强的项目。把范围收窄，给研究、原型和复盘留下空间。"
    ]
  },
  {
    "_id": "article-cmu-miips",
    "id": "cmu-miips",
    "category": "作品集",
    "title": "CMU MIIPS：把跨学科经历整理成一条清晰的申请主线",
    "excerpt": "示例摘要",
    "readTime": "3 min",
    "date": "",
    "body": [
      "示例正文仅供参考"
    ],
    "tags": [
      "CMU",
      "MIIPS",
      "录取经验"
    ],
    "status": "archived",
    "images": [
      {
        "fileID": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786934890131-0.jpg",
        "mini": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786934890131-0.jpg",
        "web": "assets/articles/cloud/cmu-miips/1786934890131-0.jpg",
        "alt": "",
        "after": 1
      },
      {
        "fileID": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786935055168-0.jpg",
        "mini": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786935055168-0.jpg",
        "web": "assets/articles/cloud/cmu-miips/1786935055168-0.jpg",
        "alt": "",
        "after": 2
      },
      {
        "fileID": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786935083635-0.webp",
        "mini": "cloud://cloud1-d9gbnehs8875905e9.636c-cloud1-d9gbnehs8875905e9-1454418571/articles/cmu-miips/1786935083635-0.webp",
        "web": "assets/articles/cloud/cmu-miips/1786935083635-0.webp",
        "alt": "",
        "after": 3
      }
    ]
  },
  {
    "_id": "article-cmu-miips-admit-notes",
    "id": "cmu-miips-admit-notes",
    "status": "archived",
    "category": "录取经验",
    "title": "CMU MIIPS：把跨学科经历整理成一条清晰的申请主线",
    "excerpt": "以 CMU MIIPS 为目标时，作品集、职业经历和文书不必各自重复，而要共同说明你如何走向产品与服务创新。",
    "readTime": "5 min",
    "date": "2026.07",
    "tags": [
      "CMU",
      "MIIPS",
      "录取经验"
    ],
    "body": [
      "MIIPS 看重的不只是项目数量，而是你能否说明自己如何在不同角色之间做判断、推动协作，并把抽象的问题落回具体的产品或服务体验。",
      "准备材料时，可以先挑出一段最能说明转折的经历：你看见了什么问题、尝试了哪些方法、哪些取舍改变了最终结果。它会成为作品集和文书共同的叙事骨架。",
      "这个练习笔记用于验证项目详情页的关联推荐功能，后续可在内容后台继续补充或下架。"
    ],
    "section": "offer"
  },
  {
    "_id": "article-umich-low-gpa-internships",
    "id": "umich-low-gpa-internships",
    "category": "录取经验",
    "title": "双非 + 3.4 GPA：如何把两段实习做成真正有用的申请材料",
    "excerpt": "这份申请没有试图掩盖 GPA，而是用前置实习和四个项目，让评审看到持续投入设计的证据。",
    "readTime": "6 min",
    "tags": [
      "UMich",
      "Pratt",
      "IIT",
      "低GPA",
      "实习",
      "作品集",
      "录取经验"
    ],
    "body": [
      "我的起点并不漂亮：双非工业设计，GPA 3.4。最后拿到 UMich、Pratt 和 IIT 的录取，并不是因为我把这个背景包装成了优势，而是因为我很早就接受了一件事：分数改不了，材料的证据结构可以重建。",
      "一开始我的选校名单几乎全是保底。我把材料拆开看了一遍，结论很明确：工业设计训练还在，两段相关实习也在，缺的是一份能把这些经历讲成设计判断的作品集。于是我没有等到申请季才找实习，而是先做出一版早期作品集，拿它去换真实工作。",
      "这个顺序替我省掉了很多无效劳动。实习不是简历上的一行字，它给项目带来真实限制、协作关系和反馈。等到我再回头做作品集时，我不需要假装理解行业，我有具体的场景、任务和取舍可以写。",
      "最后的作品集有四个项目：一个来自实习，三个为申请重新完成。我给每个项目定的标准很简单：它必须让我展示如何从工业设计的经验出发，理解用户，做取舍，再把想法落到可以被讨论的体验上。做不到这一点的项目，再漂亮也不放进去。",
      "GPA 没有在申请里消失，我也没有试图绕开它。但当材料里出现连续的行动证据，读者看到的就不再只是一个 3.4，而是一个已经用实习和项目验证过方向的人。",
      "给背景相近的人一句实话：实习不是用来“补短板”的装饰。越早用作品集去争取真实工作，申请时越有东西可讲。没有实习，也要主动给项目补上真实的约束、用户和反馈。只做漂亮画面，解决不了背景问题。"
    ],
    "status": "published"
  },
  {
    "_id": "article-ucb-mdes-architecture-to-hci",
    "id": "ucb-mdes-architecture-to-hci",
    "category": "录取经验",
    "title": "从建筑转向 HCI：这份 UCB MDes 申请没有把过去全部推倒重来",
    "excerpt": "从建筑到交互设计，真正要解决的不是“换四个新项目”，而是重新理解自己会如何观察空间、材料、用户和技术。",
    "readTime": "7 min",
    "tags": [
      "UCB",
      "MDes",
      "建筑转HCI",
      "作品集",
      "录取经验"
    ],
    "body": [
      "我本科读建筑，也在设计院实习过。决定转向 HCI 时，最容易犯的错误就是把建筑当成一段需要切断的历史。我没有这么做。建筑训练让我长期处理人的使用方式、空间和材料的关系，也让我习惯在限制里反复做原型。这些能力并不会因为媒介从建筑变成数字产品就失效。",
      "我用了接近一年准备申请，完成两个 App、一个实体装置和一个网站 redesign。真正耗时间的不是把界面画得更精致，而是不断追问：问题是怎么被发现的？这个方案为什么成立？原型替我排除了什么？没有判断过程，项目就只是截图。",
      "从建筑转交互，最危险的是急着把所有东西压成 UI，仿佛界面越多就越像 HCI。我刻意保留了实体交互和空间经验，让项目有不同的媒介和尺度。这样作品集才不是四个孤立作业，而是在回答我如何理解体验发生。",
      "最后我拿到了 UC Berkeley MDes 的录取。回头看，最有效的策略从来不是先学哪个软件，而是先把旧背景里的可迁移能力找出来，再决定哪些新项目真的值得做。",
      "如果你来自建筑、工业设计、景观或空间相关专业，不需要急着证明自己已经是成熟的 UX 设计师。你只需要把自己的思考方式讲透，再拿具体经历证明它已经开始在新的媒介里工作。"
    ],
    "status": "published"
  },
  {
    "_id": "article-uw-hcde-sop-review",
    "id": "uw-hcde-sop-review",
    "category": "文书",
    "title": "和一位参与过 UW HCDE 招生的人聊完，我记下了这三件事",
    "excerpt": "材料不是彼此独立的作业。SOP 提出线索，简历和作品集负责把线索落到证据上。",
    "readTime": "5 min",
    "tags": [
      "UW",
      "HCDE",
      "文书",
      "SOP",
      "简历",
      "申请经验"
    ],
    "body": [
      "前阵子和一位曾参与 UW HCDE 招生流程的朋友吃饭，聊到申请材料怎么读。他反复强调的不是某一份材料“最重要”，而是它们能不能互相对得上。以下是那次聊天的个人笔记，不替代项目当年的官方要求。",
      "01｜SOP 往往是阅读材料的入口",
      "招生老师面对的是一整个材料包，不一定机械地按照同一顺序阅读。但一篇清楚的 SOP 会给后面的阅读提供线索：如果文书里提到一段有意思的实习或研究，读者自然会去简历和作品集里找对应的细节。",
      "所以，材料之间最值得检查的不是“有没有重复”，而是有没有呼应。SOP 讲转折，简历交代你负责过什么，作品集把判断过程和结果展开。三份材料说的是同一个人，但每份各自完成不同的任务。",
      "02｜最容易让人失去耐心的，是没有落点的宏大表达",
      "有些文书花了很长篇幅谈公平、技术、社会议题或个人信念，却没有说清自己想进入什么方向，也没有拿经历证明这种兴趣从何而来。观点可以有，但需要落回工作和学习的选择：你看见过什么问题，做过什么尝试，接下来为什么想继续。",
      "03｜简历不需要变成奖项清单",
      "简历的任务很直接：让读者快速理解你的角色、行动和影响。每段经历都尽量说明你做了什么，而不是只写团队做了什么；有可以量化的结果就给出范围或结果。和申请方向有关的工作、实习、研究或项目，通常比零散奖项更能帮助读者判断你能带来什么。",
      "最后把三份材料摊开核对一次：SOP 里的核心经历，简历里找得到吗？作品集有没有一个项目能让人看见同样的能力？如果答案是否定的，不一定要重做材料，先想想这条叙事线是不是挑错了。"
    ],
    "status": "published"
  },
  {
    "_id": "article-uw-msti-landscape-to-product",
    "id": "uw-msti-landscape-to-product",
    "category": "录取经验",
    "title": "风景园林转向产品：UW MSTI 奖学金申请里的主线怎么搭",
    "excerpt": "景观、设计院实习、PM 体验和新作品集看起来很散，真正的工作是把它们整理成一条关于产品判断的路径。",
    "readTime": "6 min",
    "tags": [
      "UW",
      "MSTI",
      "奖学金",
      "风景园林",
      "PM",
      "转专业",
      "录取经验"
    ],
    "body": [
      "我本科和研究生都读风景园林，GPA 3.5，做过两段设计院实习，也有过大厂 PM 的体验。最后拿到 UW MSTI 的录取和 12,000 美元奖学金，同时收获 IUB、Parsons 的录取。我的背景看上去很散，但我从一开始就没有试图把它伪装成单一的 UX 履历。",
      "景观、设计院和产品的媒介不同，底层判断却相通：先理解使用场景，再把模糊需求变成可协作的方案，最后在不同利益相关者之间做选择。申请材料要做的不是给每段经历贴上 UX 标签，而是把这条能力线拉直。",
      "我的作品集由一个 PM 实习项目、三个为申请完成的 UI / UX 项目和两个景观相关的互动项目组成。这个结构不是为了凑数量。PM 项目提供真实工作的复杂度，UI / UX 项目证明产品表达能力，景观互动项目则保留我原来最有辨识度的训练。每个项目都有自己的位置。",
      "白天实习、晚上做作品集和写文书，时间非常紧。所以我不把题目做大，只给每个项目一个明确任务。能说明真实经验的项目就不要再塞成概念练习；需要补足新方向的项目，就把产品判断做完整。取舍清楚，速度才会起来。",
      "这类跨专业申请不需要一份无缝的履历。真正需要的是让人相信：我已经在不同场景里反复练习同一类判断，读 MSTI 是顺着这条线往下走，不是一次突然的逃离。"
    ],
    "status": "published"
  },
  {
    "_id": "article-consulting-to-uw-hcde",
    "id": "consulting-to-uw-hcde",
    "category": "录取经验",
    "title": "从商业咨询转向 HCI：我没有从零开始做四个设计项目",
    "excerpt": "对转行申请者而言，旧项目不一定是包袱。关键在于能否把策略、协作和决策过程重新讲成设计问题。",
    "readTime": "6 min",
    "tags": [
      "UW",
      "HCDE",
      "咨询转行",
      "作品集",
      "录取经验"
    ],
    "body": [
      "我本科读商科，毕业后在美国做了两年商业咨询。决定申请 HCI 时已经八月，留给作品集的时间很少。我的第一个判断是错的：我以为必须从零开始做一整套设计项目。后来我把过去的项目全部摊开，发现真正该做的是先找出其中已经存在的设计能力。",
      "咨询项目里本来就有策略设计、跨平台协作、媒体传播和用户相关的判断。问题不在于它们“不够设计”，而在于原来的叙述更像商业案例：目标、结论和 ROI 很清楚，但用户、流程与取舍都被藏起来了。",
      "我挑出两个最有潜力的案例，重写问题、参与者、服务流程和我自己的行动，再补上帮助读者理解方案的 diagram 和必要的界面表达。我没有给旧项目硬加几张 UI。我要的是让它们回答一个设计项目该回答的问题。",
      "十月底，我完成前两个重构项目；之后两个月，我又完成两个新的产品设计项目，赶上申请提交。最后拿到 UW 相关项目、CMU MIIPS、IUB 和 Parsons 的录取。",
      "这段经历让我非常确定：跨专业作品集的第一步不总是画图。先盘点自己真正做过什么，再判断哪些经验能够被诚实地重述为用户、系统、协作或产品问题。把已有项目讲透，比匆忙堆四个空项目有用得多。"
    ],
    "status": "published",
    "section": "offer",
    "programIds": [
      "us-010-university-of-washington-uw-ms-in-human-centered-design-engi"
    ]
  },
  {
    "_id": "article-tud-european-hengshui-misunderstanding",
    "id": "tud-european-hengshui-misunderstanding",
    "category": "就读体验",
    "title": "放弃阿尔托来到代尔夫特，我才发现“欧洲衡水”是个误会",
    "excerpt": "代尔夫特的强度确实存在，但它并不把学生推向彼此比较。一个在读学生讲述自己如何在高要求中重新学会探索、反思与松弛。",
    "readTime": "9 min",
    "tags": [
      "TUD",
      "TU Delft",
      "DfI",
      "就读体验",
      "设计教育"
    ],
    "status": "published",
    "content": [
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "拿到EIT（阿尔托+瑞典皇家理工）和代尔夫特理工两个offer的时候，身边几乎所有人都以为我会去北欧。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我没去。放弃的理由说出来有点任性：我想在硕士阶段多探索自己，而不是一头扎进一个已经选好的方向。EIT偏编程和创业，更适合\"认准一个点往死里挖\"的人；代尔夫特是所理工大校，各个方向的研究都有，更像一个可以随便逛的空间。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "当然，来之前我也没少刷到它的传言。中文互联网把代尔夫特叫\"欧洲衡水\"：课多、任务重、同学卷，读个书像坐牢。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "现在我在TUD读研，想认真说一句："
          },
          {
            "text": "衡水的部分是真的，但它卷的方向，和我理解的内卷根本不是一回事。",
            "strong": true
          },
          {
            "text": "我甚至觉得，自己恰恰是在这所学校学会了\"松弛\"。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/1-tud-library-cone.png",
        "webSrc": "assets/articles/tud-series/1-tud-library-cone.png",
        "alt": "代尔夫特理工大学图书馆（Mecanoo设计），屋顶的绿色草坡上总是坐满晒太阳和讨论作业的学生"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "毕业确实难，但难的不是\"卷\""
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "先说传言里最硬核的一条：毕业难。这条是真的。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "TUD的毕业难度是出了名的，很多国际学生延毕几个月很正常，荷兰本地学生也大多读三年而不是两年。学校要求学生每天记录各种东西，网上搜TUD就读体验，高频词是\"头大\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "但我很快发现，这种\"难\"和国内的\"卷\"是两种机制。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "TUD难在让你记录、让你反思、让你用理论审视自己的设计过程。我们有一门设计方法论课，讲reflective in action和reflective on action，意思是设计师要在过程中不断反思，而不是\"找到问题、解决、完事\"的直线逻辑。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "而且说实话，刚开学那阵我还觉得课不够多，闲到去报了荷兰语课。这和想象中\"被课程压垮\"的衡水，差得有点远。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "TUD的压力不来自排名和比较，而来自和问题本身较劲。它不催你产出，甚至不给你标准答案。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/2-tud-aula-sign.png",
        "webSrc": "assets/articles/tud-series/2-tud-aula-sign.png",
        "alt": "校园里那行TU Delft字母装置，背后是Aula会议中心"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "教授不点评你的效果图，只问\"为什么\""
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "真正让我\"文化休克\"的，是这里的课堂。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "听一位从TUD建筑系毕业、现在做设计教育的学姐讲过一个段子：她当年第一次展示作业，斥巨资打印了一张A0海报，结果荷兰同学把几张A4草稿随意往墙上一贴，就开始讲故事。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"他们非常会storytelling，表达比实际做的多十倍。我们中国学生正好相反，表达可能只有画图能力的十分之一。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "更扎心的是，她精心准备的效果图，教授一句没提，开口就问：\"你为什么要做一个X型交叉空间布局？\"他甚至不点评图画得怎么样。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"轻呈现，重思考\"，是这位学姐对TUD最深的印象。后来她做了导师，客户说要\"年轻化\"的设计，她第一反应是问\"为什么提出年轻化\"——是想要年轻人的购买力，还是想推新产品线，或者只是换个氛围？"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "用她的话说：荷兰同学做了100个从0到1，中国学生做了1个从1到100。荷兰学生敢为天马行空的想法反复试错，甚至敢用一堆荒唐的理由反驳教授，而教授会笑着听完。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/3-tud-ceremony.jpg",
        "webSrc": "assets/articles/tud-series/3-tud-ceremony.jpg",
        "alt": "代尔夫特的学位授予仪式"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "这所学校，反而不push你"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "最反直觉的是：以强度著称的代尔夫特，骨子里是反push的。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "学校专门研究设计师的resilience（弹性/恢复力），官方出过一本小册子，叫《The Resilient Designer's Handbook》，里面有一句话我特别喜欢：\"Find purpose by embracing the journey, and go beyond your comfort zone.\"（在旅程中找到意义，然后走出舒适区。）"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我把它翻译成\"松弛感\"：在一个支持性的环境里，跟随内心自由探索，允许随机事件发生。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "这种松弛是制度化的。每周三有4个workshop，可以是智能织物的编程制作，可以是谷歌员工来讲怎么用AI辅助设计，也可以是学生自己开的课——我有个同学建模好，就自己开了workshop。从下一届开始，课程模式也改了，除了固定课程，其余自主选择。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "连\"不努力\"都被允许。我们班有位同学一周没推进项目，meeting时直接跟老师说\"最近状态不好，没时间思考\"，老师没有施压，反而让大家一起集思广益。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "学校的态度很清楚：它不要求学生有多好的成果产出，也不认为一个好的创意是push出来的。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "松弛不等于躺平"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "看到这里你可能想问：那不就是躺平吗？"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "不是。TUD的松弛，建立在极高的自主性要求上。它不安排你，你得自己决定成为什么样的人。这里默认一条规则：没人会主动发现你。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我上学期听了一节AI设计研究的讲座，课后主动发邮件联系了那位老师，附上申请时的作品集，就这么进了他的实验室。后来老师办AI conference，我这个社恐i人硬着头皮去了，发现一个人待着只会更恐惧，干脆主动找人聊天。一圈下来，别人知道了我在做什么，我也看见了更大的世界。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "学校旁边的咖啡馆，周三晚上会摆出高桌，大家边喝酒边聊天。不加入的话，你永远不会知道自己会认识什么样的朋友。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "TUD给我的不是一条安排好的赛道，而是一扇窗。窗外有什么，得自己去看、自己去够。它逼我做的唯一一件事，是走出舒适区，主动成为自己，而不是等着被挑选。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/4-tud-bike-student.png",
        "webSrc": "assets/articles/tud-series/4-tud-bike-student.png",
        "alt": "骑自行车穿过校园，是代尔夫特学生的日常"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "写在最后"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "回看这段时间，我最大的变化是走出了\"优绩主义\"——那种鼓励你拿高分、用尽全力证明自己的教育，我开始对它保持警惕。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特到底是不是\"欧洲衡水\"？我的答案是：它强度很高，但从不要求你和别人比；它不给标准答案，却逼你直面\"为什么\"；它允许你停下来，前提是你知道自己要去哪。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "最后把我在TUD的收获送给大家，也送给自己："
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"不过于轻视、不过度担忧，随着时代而变，以一定的松弛/弹性去容纳各种可能，也容许自己去做各样的尝试与犯错。\""
          }
        ]
      }
    ]
  },
  {
    "_id": "article-tud-why-chinese-students-tense",
    "id": "tud-why-chinese-students-tense",
    "category": "就读体验",
    "title": "中国学生为什么“紧张”？我在代尔夫特第一次看到了另一种学生",
    "excerpt": "从 studio review 里的 A4 草稿开始，一位在读学生重新理解了“怕做错”如何影响表达，以及教育怎样给人犯错的空间。",
    "readTime": "6 min",
    "tags": [
      "TUD",
      "TU Delft",
      "设计教育",
      "就读体验",
      "Studio"
    ],
    "status": "published",
    "content": [
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "来代尔夫特之前，我刷到一个网球教练的视频。字幕里说：\"the Chinese are the most tense people I've ever seen.\"中文翻译：\"中国人是我见过的最紧张的人。\""
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/7-tud-tennis-coach.png",
        "webSrc": "assets/articles/tud-series/7-tud-tennis-coach.png",
        "alt": "网球教练视频里那句著名的话：\"中国人是我见过的最紧张的人。\""
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "当时我笑了——我们就是这样，怕做错、怕出丑、怕给别人添麻烦。但笑完我也问自己：这种紧张从哪来？它真的让我们变强了，还是只让我们变\"紧\"了？"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "直到在代尔夫特上了一整年的课，我才慢慢有了答案。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "第一次看到的反差"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "开学第一个月，我被拉去参加一个设计studio review。四五个荷兰同学站在一块大白板前，板上贴着几排便利贴和A4草稿，看起来像草图板多过正式汇报。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/5-tud-studio-review.png",
        "webSrc": "assets/articles/tud-series/5-tud-studio-review.png",
        "alt": "设计studio review，荷兰同学在便利贴和A4草稿前讲故事"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "但他们一张口就讲了五分钟。讲自己为什么想做这个、为什么这个方向有意思、为什么这个用户值得研究。我看到的不是图，是故事。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "老师打断过一次，问：\"你这个假设的依据是什么？\"荷兰同学立刻列了一堆理由反驳，有些理由我自己听着都觉得离谱。但老师笑了，说：\"你这个角度我没想过，可以试试。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我身边的中国同学大多数没说话。有一位刚去的时候，甚至只点头和摇头。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "A0海报 vs A4草稿"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "后来我听一位从TUD建筑系毕业的学姐讲过她当年的故事——她花了上千块打印了一张A0海报，带去第一次课展示。结果荷兰同学只贴了四张A4草稿就开始讲故事。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"他们非常会storytelling，\"她说，\"荷兰学生的表达比他们实际做的多十倍。我们中国学生正好相反，表达可能只有画图能力的十分之一。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "有人后来总结得很好：\"荷兰同学做了100个从0到1，中国学生做了1个从1到100。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "第一次听这话我有点不服。但看了几轮studio review，我服了。荷兰同学愿意为天马行空的想法做很多次试错，哪怕错了也敢再讲一遍。中国同学更愿意把一个已经想清楚的东西打磨到无懈可击，再拿出来。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/6-tud-maker-space.jpg",
        "webSrc": "assets/articles/tud-series/6-tud-maker-space.jpg",
        "alt": "工业风的studio里，荷兰同学用小木块搭建筑模型，不急着做完，先讲故事"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "两种风格各有所长。但在中国学生身上，我看到更多的是\"不敢开始\"，而不是\"做不完美\"。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "紧张不是能力，是习惯"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "那位学姐后来做了设计导师。她在课堂上最常用的方法，不是教技法，是先让学生放松下来。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"前几次课我通常不急着讲具体做什么，\"她说，\"我会和他们聊生活，聊他们以前的课程。我让他们讲自己的故事。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "等学生放松了，她才开始引导。\"等心态放松，中国学生的学习能力和执行力是所有国家里最好的。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "她这句话让我重新理解了\"紧张\"——它不是能力问题，是习惯问题。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "TUD怎么治这个"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特治\"紧张\"的方式很有意思。它不是让你别紧张，而是给你犯错的空间。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "每周三有4个workshop，可以是智能织物、可以是亲密关系设计、也可以是学生自己开的课；从下一届起，课程也改成可选的。我们班有同学一周没推进项目，meeting时直接说\"最近状态不好，没时间思考\"，老师让大家集思广益。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/11-tud-metal-grinder.jpg",
        "webSrc": "assets/articles/tud-series/11-tud-metal-grinder.jpg",
        "alt": "打磨金属的工坊场景，学生在动手做原型，不怕做错，边做边改"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "它用一整年的\"允许失败\"，把\"怕做错\"那根弦慢慢拆掉。等你发现做错没什么大不了的时候，你才会开始真正去想\"为什么\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "中国学生不缺能力。我们缺的，是\"我做了一个不完美的方案，也能理直气壮地讲出来\"的练习。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "写在最后"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "那位网球教练后来在他的视频里说，他每次教中国人，会先花一个小时让他们放松下来。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特不花一小时，但用了一整年。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我现在回头看这段经历，觉得它教给我的，不是怎么画图、怎么做模型，而是怎么样先承认\"我不知道\"，再从那里开始走。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "紧张不是我们的错。但知道紧张在哪一步松绑，可能是这一代中国学生最值得学的一课。"
          }
        ]
      }
    ]
  },
  {
    "_id": "article-tud-harvard-ranking-application-strategy",
    "id": "tud-harvard-ranking-application-strategy",
    "category": "申请经验",
    "title": "哈佛输给代尔夫特19名之后，我的申请策略也跟着改了",
    "excerpt": "从排名走向项目匹配：一位 DfI 申请者拆解三大项目、作品集逻辑和自己最终如何做选校决定。",
    "readTime": "8 min",
    "tags": [
      "TUD",
      "TU Delft",
      "DfI",
      "IPD",
      "SPD",
      "申请经验",
      "选校"
    ],
    "status": "published",
    "content": [
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "2025年EduRank的人机交互（HCI）排名出来的时候，我正在申请季的尾巴上。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "看到那条新闻\"CMU第一、MIT第二、斯坦福第三，代尔夫特第14，哈佛没进前30\"，我反而松了口——不是因为代尔夫特比我申请的那些学校强，是因为它让我意识到：我之前太执着\"名校光环\"了。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/14-tud-science-centre.png",
        "webSrc": "assets/articles/tud-series/14-tud-science-centre.png",
        "alt": "代尔夫特Science Centre，留学申请的起点"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"哈佛在定义问题，代尔夫特在解决问题。\"这个总结，我申请完才真正理解。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "我的背景和选校逻辑"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我本科是交互设计，有过几个完整的设计项目，作品集里有产品也有服务设计方向。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "选校那会儿我把目标分成两类：一类是\"金字招牌型\"（CMU、RISD、皇艺），一类是\"研究方向型\"（代尔夫特、EIT、阿尔托）。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我的逻辑很简单：牌子不能当饭吃。如果花两年时间在一个不贴合我研究兴趣的项目里，毕业再发现方向不对，那就比延毕更贵了。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "后来我拒了所有\"金字招牌型\"学校，选了代尔夫特的Design for Interaction（DfI）项目。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "三大项目怎么选"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特的设计学院有三个跟交互沾边的硕士项目，选之前我纠结过很久："
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "DfI（Design for Interaction）",
            "strong": true
          },
          {
            "text": "——关键词：以人为本、社会共感。把\"设计\"理解为跟人打交道的实践。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "IPD（Integrated Product Design）",
            "strong": true
          },
          {
            "text": "——关键词：技术融合、原型实践。把\"设计\"理解为工程师的延伸。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "SPD（Strategic Product Design）",
            "strong": true
          },
          {
            "text": "——关键词：设计战略、社会创新。把\"设计\"理解为组织的转型工具。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我选DfI，因为我的兴趣是\"人和技术怎么对话\"，不是\"产品怎么做出来\"，也不是\"战略怎么落地\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "如果你对硬件/原型/制造更感兴趣，IPD可能更合适；如果你以后想做design strategy或创业，SPD更合适。这三个不冲突，但选错了会影响两年的方向。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "申请要求 checklist"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "把我当时整理的清单分享出来："
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "学历材料",
            "strong": true
          },
          {
            "text": "：本科毕业证+翻译、成绩单+翻译、GPA ≥ 75%（同等成绩可）。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "英语",
            "strong": true
          },
          {
            "text": "：IELTS ≥ 7.0（单项 ≥ 6.5）/TOEFL iBT ≥ 100（单项 ≥ 22）/Cambridge C1·C2 ≥ 185，2年内成绩。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "作品集",
            "strong": true
          },
          {
            "text": "：3–8个项目，至少1个完整设计过程，PDF ≤ 20MB、≤ 30页、A4横版，可附视频链接。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "其他",
            "strong": true
          },
          {
            "text": "：动机信（写你为什么来+你想做什么）、简历、1–2封推荐信。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "作品集我花了大概4个月。3-8个不多，但每一个都要有自己的\"完整故事\"。我最满意的项目是一个假肢超材料的设计，从用户研究到原型到验证，一气呵成。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "作品集审稿人只看几秒钟"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "后来我从一位审过作品集的教授那里听到一个细节：初审每份只花几秒钟。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/12-tud-design-meeting.jpg",
        "webSrc": "assets/articles/tud-series/12-tud-design-meeting.jpg",
        "alt": "设计studio里的小组讨论，作品集的内容就是这种讨论场景的浓缩"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "这意味着：你不能用\"我做了很多很复杂的东西\"来打动审稿人。你需要让他们在三秒内知道\"你是谁，你在想什么\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我的经验："
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "第一个项目放最有\"个人特质\"的，不要放最\"漂亮\"的。"
            }
          ],
          [
            {
              "text": "文字 caption 要有\"我为什么这么做\"，而不只是\"我做了什么\"。"
            }
          ],
          [
            {
              "text": "视频/动效不超过1分钟，留链接即可。"
            }
          ],
          [
            {
              "text": "整体排版要克制。"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "面试和动机信"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "DfI没有正式面试，但动机信权重很高。我最后一遍改动机信花了两周，把它从\"我想申请贵校\"改成了\"我带着三个具体问题想来贵校\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "有朋友申EIT的时候被要求交一个创业提案，我帮她改了三遍，核心是\"问题比方案重要\"。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/9-tud-workshop-collage.png",
        "webSrc": "assets/articles/tud-series/9-tud-workshop-collage.png",
        "alt": "Workshop里学生用智能织物、互动物件做原型，这种动手的项目也常出现在作品集里"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "拿到offer之后"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "拿到DfI的offer之后，我做了一件后来看很重要的事：联系老师。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我听了一节AI设计研究的讲座，课后主动发邮件，附上作品集，就这么进了老师的实验室。这件事改变了我的整个硕士经历——不是你坐在教室里被动接收，而是你主动走进研究。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/17-tud-breast-implant-design.png",
        "webSrc": "assets/articles/tud-series/17-tud-breast-implant-design.png",
        "alt": "毕业设计展上，胸假体概念项目展示了设计师如何回应真实的女性身体需求"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "写在最后"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特在排名里输给哈佛，不是因为它不好，是因为它们的教育哲学不一样。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "哈佛在培养\"定义问题的人\"，代尔夫特在培养\"解决问题的人\"。两种人都需要，但如果你像我一样，想知道\"自己做的设计怎么落地\"，代尔夫特可能更适合你。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "至于哪个学校更适合你——这问题没有标准答案。但有一件事是确定的：申请季最忌讳的，是按别人的模板做自己的选择。"
          }
        ]
      }
    ]
  },
  {
    "_id": "article-tud-typical-week-in-interaction-design",
    "id": "tud-typical-week-in-interaction-design",
    "category": "就读体验",
    "title": "在代尔夫特读交互设计：一个硕士的典型一周",
    "excerpt": "从周三 workshop、跨学科课堂到实验室和咖啡馆里的 networking，一位在读学生记录了代尔夫特硕士生活的实际节奏。",
    "readTime": "7 min",
    "tags": [
      "TUD",
      "TU Delft",
      "DfI",
      "Workshop",
      "就读体验"
    ],
    "status": "published",
    "content": [
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "早上九点，我骑车穿过校园，拐进Mekelweg那条两排都是梧桐的大道。九月的阳光从树叶间漏下来，落在新建的IDE教学楼玻璃幕墙上，折射到我的手背上。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我把车锁在楼下的停车棚，和十几个早到的同学一起刷卡进楼，坐电梯上三楼。一周就这么开始了。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/8-tud-orange-staircase.jpg",
        "webSrc": "assets/articles/tud-series/8-tud-orange-staircase.jpg",
        "alt": "橙色楼梯的工业风教学楼，学生随时在楼梯上坐下来讨论项目"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "周三的 workshop"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特最有特色的是周三的workshop。固定有4场，主题每周都不一样。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我上学期上过："
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "智能织物编程（用导电纤维做了一件会发光的衣服）"
            }
          ],
          [
            {
              "text": "谷歌员工来分享怎么把用户研究数据接入AI工作流"
            }
          ],
          [
            {
              "text": "一场关于\"亲密关系中的设计与性\"的研讨会（尺度非常开放）"
            }
          ],
          [
            {
              "text": "一个同学自己开的workshop，讲Houdini的粒子特效"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "workshop不计入正式学分，但每个人都被\"鼓励\"参加。学校把这当作\"打开视野\"的窗口，不是让你变成专家，而是让你知道\"还有这种东西存在\"。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/10-tud-emotion-workshop.png",
        "webSrc": "assets/articles/tud-series/10-tud-emotion-workshop.png",
        "alt": "情绪设计workshop，学生用颜色、灯光、声音模拟恐惧、羞耻、惊讶、喜悦四种情绪"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "跨学科的课"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特是所理工大校，跨学科的资源比设计学院多很多。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我上学期选了一门\"技术与社会\"的通识课，老师是电气工程学院的。整个课堂一半是工科生，一半是设计生。第一次小组讨论，工科同学直接说：\"你们做的东西没有scalability。\""
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我当场有点难受。但两周后我理解了：他们说的不是\"我们做的不对\"，而是\"在他们的评估体系里，我们做的不算研究\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "这种碰撞比单一学科内部的学习更值钱。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/15-tud-high-voltage-lab.jpg",
        "webSrc": "assets/articles/tud-series/15-tud-high-voltage-lab.jpg",
        "alt": "高压电气实验室，设计学生可以走进这类科研设施，了解工程学科的研究方法"
      },
      {
        "type": "heading",
        "level": 2,
        "text": "实验室合作"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我读交互设计，但我每周会在两个实验室里出没：一个是AI设计研究组，另一个是动作捕捉实验室。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "AI设计研究组的项目是\"如何用LLM协助设计研究的过程\"；动作捕捉实验室是帮电影和游戏行业做虚拟人原型。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "这两个实验室最大的不同是节奏——AI组每周两个meeting，大家快速迭代；动作捕捉组两周一次，但每次都要进真正的动捕棚。"
          }
        ]
      },
      {
        "type": "image",
        "miniSrc": "/assets/articles/tud-series/16-tud-motion-capture.png",
        "webSrc": "assets/articles/tud-series/16-tud-motion-capture.png",
        "alt": "动作捕捉实验室，学生在棚里表演动作，屏幕里实时渲染虚拟人骨架"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我选择跨两个实验室，代价是时间被切得很碎。但收益是——我比大多数同学更早知道自己毕业后想做什么。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "Networking 不是\"认识大佬\""
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我之前理解的\"networking\"是\"认识更多厉害的人\"。来代尔夫特之后，我才发现 networking 的核心是\"主动展示自己\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我第一次去AI conference的时候，作为一个社恐i人，我本来只想坐在角落。结果一个人呆着比主动找陌生人更恐惧。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我硬着头皮走过去问：\"你这个poster做的是什么？\"对方讲了五分钟，我也讲了五分钟。一圈下来，我们互相知道了对方在做什么，后续就有了合作的可能。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "学校里每周三晚上，旁边的咖啡馆会摆高桌，大家边喝酒边聊天。不加入的话，你永远不会知道自己会认识什么样的朋友。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "周末的代尔夫特"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "周末一般会骑车去鹿特丹或者海牙。荷兰小，火车半小时到任何地方。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "我会带一个速写本，坐在运河边画半小时，画完去找一家brunch店写周报。这种\"切换场景+记录\"的学习方式，我觉得比死守书桌有效得多。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "写在最后"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "很多人问我\"代尔夫特累不累\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "累。课业压力真实存在。但这种累不是\"被迫赶due\"，而是\"我想把一个项目打磨得更好\"。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "代尔夫特给学生的不是一条安排好的赛道，而是一扇窗。窗外有什么，你得自己去看、自己去够。"
          }
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "这一年的节奏，大概是\"周中紧张、周末松弛\"。这种状态，我觉得刚刚好。"
          }
        ]
      }
    ]
  },
  {
    "_id": "article-tud-experience-material-library",
    "id": "tud-experience-material-library",
    "category": "资料整理",
    "title": "代尔夫特理工大学（TU Delft）就读经验素材库",
    "excerpt": "从课堂里的 A0 海报与 A4 草稿，到三大项目的申请要求和在读学生的观察：一份交叉整理的代尔夫特资料库。",
    "readTime": "16 min",
    "tags": [
      "TUD",
      "TU Delft",
      "DfI",
      "IPD",
      "SPD",
      "申请经验",
      "就读体验"
    ],
    "status": "published",
    "content": [
      {
        "type": "quote",
        "segments": [
          {
            "text": "整理时间：2026-08-11 素材来源：三篇微信公众号文章（详见下表），供后续创作文章使用。 整理方式：逐篇精读 → 保留原文细节与金句 → 按主题交叉归类。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "一、素材来源总览"
      },
      {
        "type": "table",
        "rows": [
          [
            "#",
            "文章标题",
            "来源公众号",
            "发布时间",
            "分享人",
            "身份背景",
            "切入视角"
          ],
          [
            "1",
            "第一次在代尔夫特上课，我精心准备了A0海报，教授却喜欢荷兰同学的A4草稿",
            "一只梨",
            "2026-07-23",
            "晓宁",
            "本科中国美术学院，硕士TUD建筑，曾就职West8、AECOM等顶级事务所",
            "导师/教育理念视角"
          ],
          [
            "2",
            "人机交互的未来不在藤校？哈佛，输给代尔夫特19名！",
            "一只梨",
            "2025-10-21",
            "一只梨编辑部（含学员zeqi、田老师）",
            "交互设计留学机构，EduRank排名解读",
            "排名/项目/申请视角"
          ],
          [
            "3",
            "放弃阿尔托，我来到代尔夫特理工",
            "汉艺国际",
            "2024-03-15",
            "C同学",
            "H·ART 22届学员，TUD交互设计MSc在读",
            "在读学生亲历视角"
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "三篇文章恰好构成完整三角："
          },
          {
            "text": "导师眼中的教育哲学（文章一）＋ 机构眼中的排名与申请（文章二）＋ 学生眼中的真实就读体验（文章三）",
            "strong": true
          },
          {
            "text": "，可以互为印证、交叉引用。"
          }
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "二、文章一：晓宁老师——代尔夫特教的是\"思考与判断\""
      },
      {
        "type": "heading",
        "level": 3,
        "text": "作者背景"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "本科：中国美术学院；硕士：代尔夫特理工大学（建筑学）"
            }
          ],
          [
            {
              "text": "毕业后曾就职于 West8、AECOM 等国际顶级建筑事务所"
            }
          ],
          [
            {
              "text": "现为\"一只梨\"设计思维、基础课导师，教设计思维、视觉基础、作品排版"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "核心叙事1：一堂课引发的文化冲击（A0海报 vs A4草稿）"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "晓宁为展示作业斥巨资打印 A0 大小海报，荷兰同学却把几张 A4 草稿随意贴到墙上就开始\"讲故事\""
            }
          ],
          [
            {
              "text": "核心对比金句："
            }
          ],
          [
            {
              "text": "\"他们非常会storytelling。荷兰学生的表达比他们实际做的似乎多十倍。\""
            }
          ],
          [
            {
              "text": "\"作为中国学生，我们正好相反。我们的表达可能只有画图能力的十分之一。\""
            }
          ],
          [
            {
              "text": "荷兰学生为天马行空的想法做大量尝试；教授提出质疑时，荷兰同学会列出一堆理由反驳——有些理由很荒唐，教授甚至会笑着听完"
            }
          ],
          [
            {
              "text": "结论性比喻："
            },
            {
              "text": "\"荷兰同学做了100个从0到1，中国学生做了1个从1到100。\"",
              "strong": true
            }
          ],
          [
            {
              "text": "观点延伸：\"你做了什么当然重要，但别人更愿意为你创造出来的需求、真正击中痛点的想法买单。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "核心叙事2：轻呈现，重思考——\"问为什么\""
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "晓宁曾花大量时间准备精美效果图，教授一上来却问：\"你为什么要做一个X型交叉空间布局？\"——\"他甚至不点评效果图画得怎么样！\""
            }
          ],
          [
            {
              "text": "TUD 鼓励学生用模型帮助思考（轻呈现、重思考）"
            }
          ],
          [
            {
              "text": "对代尔夫特教育最直观的印象就是\"问为什么\"，如今已成为她自己的职业习惯"
            }
          ],
          [
            {
              "text": "追问方法论的完整案例（客户要\"年轻化\"设计时）："
            }
          ],
          [
            {
              "text": "第一层追问：为什么提出年轻化？→ 是品牌要引入年轻人购买力 / 发展新商业模式 / 推出新产品系列？"
            }
          ],
          [
            {
              "text": "第二层追问：这个空间未来会做什么？是吸引年轻人购买力，还是只想改变空间氛围？"
            }
          ],
          [
            {
              "text": "金句：\"很多时候，无法很好回答一个问题，是因为没有真正理解问题是什么，却已经开始行动。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "核心叙事3：紧张的中国学生与教育的本质"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "网球教练视频类比：美国人进攻性强、日本人极致防守、法国人非常随性、"
            },
            {
              "text": "中国学生非常紧张",
              "strong": true
            },
            {
              "text": "——不敢做动作、很怕做错，教练每教中国学生要先花一小时让他们放松"
            }
          ],
          [
            {
              "text": "\"等心态放松、认为自己在一个安全的环境里，中国学生学习能力、执行力是所有国家里最好的。\""
            }
          ],
          [
            {
              "text": "教学启示：\"前几次课，甚至前五次课，我通常不急着讲具体做什么。\"先让学生讲过去的课程/项目、从生活观察切入，学生放松后才愿意表达"
            }
          ],
          [
            {
              "text": "教育观核心句："
            },
            {
              "text": "\"未来教育不应再把重点放在技术侧，它们应该被放在第二层。第一层永远是教学生如何放大自己作为人的特性：沟通、合作、感受。\"",
              "strong": true
            }
          ],
          [
            {
              "text": "AI 时代的定位：\"真正留下来的工作，反而越来越像代尔夫特教的那些东西：思考和判断。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "AI时代，学生更需要什么（三点）"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "表达和合作",
              "strong": true
            },
            {
              "text": "：脑子里有想法却不知道如何喂给 AI，AI 就无法帮你工作；要能与其他学科的同学合作解决复杂问题"
            }
          ],
          [
            {
              "text": "观察和研究能力",
              "strong": true
            },
            {
              "text": "：AI 没有真实感受；人要能感受空间和需求，再把感受转化为文字或指令传递给 AI"
            }
          ],
          [
            {
              "text": "拥抱不确定性",
              "strong": true
            },
            {
              "text": "：AI 越发展，人越要知道如何面对不确定、处理它带来的正面或负面影响"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "行业观察：不确定性、裁员与\"去大厂化\""
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "晓宁所在公司一年多裁员约50%：\"公司可能不再需要一个人全职坐在工位上。大部分工作由AI完成，工作模式确实被完全改变。\""
            }
          ],
          [
            {
              "text": "同学案例：有同学现在在 AECOM 做豪宅装修和设计，\"以前大家是不屑做住宅的，更愿意做城市规划\""
            }
          ],
          [
            {
              "text": "自媒体兴起，学生开始轻创业，\"一个人就是一家公司\"，对\"大厂迷信\"越来越弱（行业下行 + 路径多元）"
            }
          ],
          [
            {
              "text": "\"现在路径更多元，不确定性也增加了。乐观和悲观的人，看到的是完全不同的两个世界。\""
            }
          ],
          [
            {
              "text": "心态建议：\"在自己能够得着的地方，发挥最大价值，也不用过度强迫自己。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "专业之问：建筑只是载体"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "建筑行业从繁华走向下行，网上看空远大于看多；但有网友反问：\"如果说建筑专业不行，有哪些专业是好的？\""
            }
          ],
          [
            {
              "text": "晓宁反问：\"AI能维持多少年的高速上升？\""
            }
          ],
          [
            {
              "text": "若带现在的认知重回大学：可能还学建筑，但会更早走出建筑学院，去接触商业、心理学、AI、交互，主动和不同专业的人合作"
            }
          ],
          [
            {
              "text": "金句："
            },
            {
              "text": "\"建筑只是一个载体。真正重要的是，它让我学会如何处理复杂问题。而建筑学训练的底层思维，让思维更有韧性、包容性更强。\"",
              "strong": true
            }
          ],
          [
            {
              "text": "\"行业会有周期，技术不断变化，真正能陪着一个人走下去的，往往不是专业本身，而是背后那套看世界、解决问题的方法。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "代尔夫特\"小道消息\"：作品集评审真相"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "初筛作品集，每份只有几秒钟"
            }
          ],
          [
            {
              "text": "反面案例：见过一个作品集有5个作品、分别由不同老师完成、非常割裂——\"看完以后，完全不知道这个学生是谁！\""
            }
          ],
          [
            {
              "text": "结论：出彩的作品集必须有"
            },
            {
              "text": "完整性",
              "strong": true
            },
            {
              "text": "；完整性 + storytelling 很重要，要让人迅速看到你是谁、你的个人身份和特质"
            }
          ],
          [
            {
              "text": "通过初筛后，评审才会仔细看逻辑与细节——\"是否有符合学校课程设置、能让评委感兴趣的课题。这些都是抓手。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "三、文章二：一只梨——HCI排名、三大项目与申请要求"
      },
      {
        "type": "heading",
        "level": 3,
        "text": "核心背景：2025 EduRank 人机交互（HCI）专业排名"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "排名依据：论文数量、被引次数、时间加权等科研产出维度"
            }
          ],
          [
            {
              "text": "关键名次：CMU 第1、MIT 第2、斯坦福 第3；前15名基本为美国院校"
            }
          ],
          [
            {
              "text": "代尔夫特（TU Delft）第14名——欧洲第二、荷兰第一；哈佛未进前30，与代尔夫特差距19名",
              "strong": true
            }
          ],
          [
            {
              "text": "其他亮眼非美院校：东京大学、大阪大学、多伦多大学、UCL、代尔夫特"
            }
          ],
          [
            {
              "text": "金句："
            }
          ],
          [
            {
              "text": "\"哈佛在定义问题，代尔夫特在解决问题。\""
            }
          ],
          [
            {
              "text": "\"人机交互，是一门实践学科。\""
            }
          ],
          [
            {
              "text": "\"看排名，一定要多维度一起看。这不是哈佛被低估，这是两所不同学校，对交互设计教育也有不同的理念。\""
            }
          ],
          [
            {
              "text": "代尔夫特实验室生态：学生研究成果以 "
            },
            {
              "text": "MVP原型、算法模型、用户交互验证",
              "strong": true
            },
            {
              "text": " 的形式存在，论文是自然而然的结果；当 AI 进入家居、车载、可穿戴设备等场景时，情绪识别、光影反馈、触觉信号、社会性机器人等在实验室里不断被测试、改进、落地"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "就读强度与毕业难度"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "学员 zeqi 原话：\"TuD毕业确实挺困难的！有很多的国际学生甚至会选择延毕几个月，荷兰本土学生也大多会选择三年去做这个项目，而不是两年。\""
            }
          ],
          [
            {
              "text": "学校要求学生每天记录各种东西"
            }
          ],
          [
            {
              "text": "全网探讨 TUD 学习强度，关键词是\"头大\""
            }
          ],
          [
            {
              "text": "文章态度：延毕也不完全是坏事"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "设计学院教育特色"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "交互设计教育不停留在概念或界面层面，强调"
            },
            {
              "text": "用原型去验证想法",
              "strong": true
            },
            {
              "text": "，形成\"以研究驱动设计\"的能力"
            }
          ],
          [
            {
              "text": "课程结合认知心理学、工程技术、美学思维"
            }
          ],
          [
            {
              "text": "学生常在真实企业项目中探索 AI、物联网、可持续设计等议题"
            }
          ],
          [
            {
              "text": "毕业生去向：飞利浦、宝马、宜家、耐克等国际公司，也有不少人创立自己的创新工作室"
            }
          ],
          [
            {
              "text": "毕业生评价：\"能把'人类体验'转化为'产品智能'的新一代设计者\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "三大交互设计硕士项目对比"
      },
      {
        "type": "table",
        "rows": [
          [
            "维度",
            "DfI 交互设计 (Design for Interaction)",
            "IPD 集成产品设计 (Integrated Product Design)",
            "SPD 战略产品设计 (Strategic Product Design)"
          ],
          [
            "关键词",
            "以人为本、社会共感、情境体验、伦理与责任、设计即研究",
            "技术融合、可持续设计、系统思维、原型实践、创新制造",
            "设计战略、社会创新、系统协作、未来愿景、可持续转型"
          ],
          [
            "课程特点",
            "鼓励以实验方式探索人机关系边界（心理学→哲学、AI→社会创新）；在真实企业与社区项目中把复杂系统转化为有温度的体验",
            "代尔夫特最具\"工程美学\"的课程，让设计师和工程师在同一张桌子上思考未来产品形态；融合技术原型、数字制造与可持续理念",
            "将设计思维与商业战略、社会创新结合；项目常涉及政府、企业与非营利组织多方协作（如健康生活方式、AI驱动的可持续食品系统）；核心是\"通过设计推动组织转型\""
          ],
          [
            "培养目标",
            "能以设计塑造未来关系的\"社会共感者\"；既要理解人，也要引导技术",
            "让 AI、智能纺织、生物材料等新兴技术真正进入生活；具备实践能力与系统思考力，理性与创造共生",
            "从竞争走向合作，从单一创新走向生态共建"
          ],
          [
            "申请偏好",
            "设计/工程类本科",
            "设计或工程相关专业（工业设计、机械、计算机、人机交互等）；需展示设计思维与工程技术兼备",
            "设计或相关学科，**含工作经验者优先**；需展示研究能力与学术写作水平"
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "通用申请要求（三大项目基本一致）"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "学历",
              "strong": true
            },
            {
              "text": "：学士学位证书 + 翻译（或学位确认声明）；成绩单 + 翻译"
            }
          ],
          [
            {
              "text": "成绩",
              "strong": true
            },
            {
              "text": "：GPA ≥ 75%（或同等成绩）"
            }
          ],
          [
            {
              "text": "语言",
              "strong": true
            },
            {
              "text": "（2年内取得）：IELTS ≥ 7.0（单项 ≥ 6.5）/ TOEFL iBT ≥ 100（单项 ≥ 22）/ Cambridge C1·C2 总分 ≥ 185"
            }
          ],
          [
            {
              "text": "材料",
              "strong": true
            },
            {
              "text": "：动机信（Motivation Letter）、简历（CV）、推荐信（1–2封）、作品集"
            }
          ],
          [
            {
              "text": "作品集规格",
              "strong": true
            },
            {
              "text": "：3–8个项目（至少1个完整设计过程）；展示设计研究、用户研究、交互体验等能力；PDF ≤ 20MB、≤ 30页、A4横版；可附动画/视频链接"
            }
          ],
          [
            {
              "text": "其他：非荷兰学士学位可能需衔接课程（以荷兰语授课）"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "学员案例：田老师"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "罗德岛设计学院（RISD）本科毕业后，2025年正式进入代尔夫特读交互设计硕士"
            }
          ],
          [
            {
              "text": "选择欧洲的原因是\"养生\"（文章调侃：可能\"失望\"，因为 TUD 强度很大）"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "其他数据点"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "TUD 官方报道：IDE 学院有 "
            },
            {
              "text": "15篇 CHI 论文被接收",
              "strong": true
            },
            {
              "text": "，获 Best Paper / Honorable Mentions 等殊荣"
            }
          ],
          [
            {
              "text": "文章发布于 2025-10-21，明确提到 26fall 开放申请"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "四、文章三：C同学——放弃阿尔托，在TUD学会松弛"
      },
      {
        "type": "heading",
        "level": 3,
        "text": "作者背景"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "H·ART 22届学员，代尔夫特理工大学交互设计 MSc 在读"
            }
          ],
          [
            {
              "text": "申请季放弃 EIT（阿尔托大学 + 瑞典皇家理工）人机交互与设计双学位，选择 TUD"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "开篇定调：\"欧洲衡水\"的祛魅"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "\"Find purpose by embracing the journey, and go beyond your comfort zone.\"",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "来之前看到传言：\"说他（代尔夫特）是欧洲衡水、课很多、同学很卷等等\""
            }
          ],
          [
            {
              "text": "真实体验：\"但我恰恰是来了代尔夫特，学会了松弛。\""
            }
          ],
          [
            {
              "text": "学校有对设计师 resilience（弹性/恢复力）研究的小册子《The Resilient Designer's Handbook》，送给大家一句话："
            }
          ],
          [
            {
              "text": "她把 resilience 翻译成\"松弛感\"：在支持性环境中跟随自己的内心自由探索、包容随机性事件发生的状态"
            }
          ],
          [
            {
              "text": "正是这种松弛，让她走出\"优绩主义\"，看到更多元、更包容、更以人为本的设计"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "EIT vs TUD 的选择逻辑"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "EIT 申请经验",
              "strong": true
            },
            {
              "text": "（EIT = European Institute of Innovation & Technology）："
            }
          ],
          [
            {
              "text": "材料常规：语言成绩、CV、视频；比较特殊的是动机信"
            }
          ],
          [
            {
              "text": "动机信两方面内容：① 为什么要加入这个项目 ② 提出一个创业项目"
            }
          ],
          [
            {
              "text": "C同学把作品集里\"假肢超材料设计\"项目延伸、结合未来医疗定制化写进动机信"
            }
          ],
          [
            {
              "text": "EIT 未明确要求作品集（更像 mix 招生，组织编程/设计/商业等不同背景的人），但她仍放了作品集链接——作品集是彰显设计生优势的工具"
            }
          ],
          [
            {
              "text": "她投的项目偏重编程，所以在简历中强调本科相关课程 + 项目作品集的编程体现，这是优势"
            }
          ],
          [
            {
              "text": "拿到 offer 但没申到奖学金：\"奖学金的申请，算是一门玄学吧\""
            }
          ],
          [
            {
              "text": "EIT 特点",
              "strong": true
            },
            {
              "text": "：偏编程，课堂作业更多是\"写一堆代码\"而非做设计项目，适合\"设计转码\"群体；除课程外还有重要的创业部分（项目推进、人脉资源、项目扶持）"
            }
          ],
          [
            {
              "text": "TUD 特点",
              "strong": true
            },
            {
              "text": "：理工类学校，有大量其他学院资源，可跨学科合作接触不同领域知识"
            }
          ],
          [
            {
              "text": "实例：上学期有门课请学院中做不同研究的老师开讲座（情感化设计、服务设计、AI相关设计等）；C同学听完 AI 设计研究老师的课后"
            },
            {
              "text": "主动发邮件联系、附上申请时的作品集，成功加入老师实验室",
              "strong": true
            }
          ],
          [
            {
              "text": "选校结论：\"EIT项目更适合已经认准一个点，想使劲去深挖的人。\"C同学不确定自己想成为什么样的设计师，希望在硕士阶段继续探索、做更多尝试，所以选择提供\"广阔空间\"的 TUD"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "TUD 就读体验"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "课程模式改革",
              "strong": true
            },
            {
              "text": "：从下一届起 TUD 改了课程模式——除几个固定课程和项目外，学生可以自主选择其他课程，更自由；C同学这届还是学校固定安排，刚开学甚至觉得课不够多，闲到去报了荷兰语课程"
            }
          ],
          [
            {
              "text": "主动联系老师",
              "strong": true
            },
            {
              "text": "：学校会安排不同研究方向的老师开讲座讲自己的研究，遇到感兴趣的课题可主动申请加入实验室"
            }
          ],
          [
            {
              "text": "每周三 4 个 workshop",
              "strong": true
            },
            {
              "text": "："
            }
          ],
          [
            {
              "text": "智能织物的编程与制作（偏手工与技术）"
            }
          ],
          [
            {
              "text": "邀请谷歌员工讲述如何在实践中使用 AI、数据助力设计"
            }
          ],
          [
            {
              "text": "研讨会形式：一起讨论亲密关系中与性、爱相关的设计"
            }
          ],
          [
            {
              "text": "学生自组织（觉得自己建模技术好也能开 workshop）"
            }
          ],
          [
            {
              "text": "作用：\"虽然一天下来不可能把东西全学完，但这些workshop至少为我打开了一个视野，让我认识到还有这些东西的存在，并从中挖掘自己的兴趣点。\""
            }
          ],
          [
            {
              "text": "理论教学是招牌",
              "strong": true
            },
            {
              "text": "：TUD 以设计方法与设计理论著称，重视理论教学（上学期6门课中2门偏理论）"
            }
          ],
          [
            {
              "text": "design methodology 课程：教如何通过前人理论反思自己的设计过程，提到 "
            },
            {
              "text": "reflective in action（行动中反思）和 reflective on action（行动后反思）",
              "strong": true
            }
          ],
          [
            {
              "text": "观念转变：本科阶段认为\"设计是解决问题的学科\"→ 现在认识到\""
            },
            {
              "text": "解决问题、提出问题其实是一个不断交织、不断进行的过程",
              "strong": true
            },
            {
              "text": "\"，而非\"找到问题解决就得了\"的线性逻辑（先发现模糊问题→尝试性提出方法→验证方案→从中再提出问题→循环往复）"
            }
          ],
          [
            {
              "text": "老师不强制使用理论：\"他只是为你提供了一套新的工具与方法，但如何抉择、是否使用还是取决于个人。\""
            }
          ],
          [
            {
              "text": "不是衡水，不push创意",
              "strong": true
            },
            {
              "text": "：有同学一周项目没怎么推进，和老师 meeting 时直接说\"最近整个人状态不好，没时间去思考这个东西\"，还提出让大家集思广益"
            }
          ],
          [
            {
              "text": "\"它并非是要求学生有多么多么好的成果产出，也不认为一个好的创意是push出来的。\""
            }
          ],
          [
            {
              "text": "松弛的收获",
              "strong": true
            },
            {
              "text": "：\"给了我选择与犯错的空间，让我能享受设计的过程，享受对未来自由的探索\"，从制定单一竞争目标赛道中走出来；对\"鼓励人拿高分、用尽全力展现自我的教育\"保持警惕与反思"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "networking：主动出击"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "感悟：过往教育有标化评定，成绩就是标签，不需要告诉别人成绩就会替我展示实力；但出来后发现\""
            },
            {
              "text": "每个人都有自己的亮点，如果不主动地去展示自己，而是一直等待被认可甚至被挑选，基本很难被看见",
              "strong": true
            },
            {
              "text": "\""
            }
          ],
          [
            {
              "text": "案例1：主动发邮件联系老师加入实验室 → 之后受邀参加老师举办的 AI conference"
            }
          ],
          [
            {
              "text": "案例2：作为社恐 i 人参加 conference，发现一个人呆着只会更恐惧且难有收获，于是主动找人聊天，\"通过与别人不断地networking，了解到他们在做什么，他们也知道了我在做什么\"，构建人际网络的过程也是进入 conference 的过程"
            }
          ],
          [
            {
              "text": "学校旁咖啡馆，周三晚摆高桌，大家边喝酒边聊天：\"不加入，你永远不会知道自己会认识什么样的朋友，然后发生什么样的变化。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 3,
        "text": "AI 时代的设计师"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "学校有实验室在做 AI 设计研究：收集设计师设计过程中使用的语言、记录过程去训练 AI"
            }
          ],
          [
            {
              "text": "观点：\"对于写一段话、生成一张图片、甚至做三维模型，AI确实是可以做到越来越好的，但是它没有办法去'经验这个世界'。\"这也是为什么要提取设计师的语言导入 AI"
            }
          ],
          [
            {
              "text": "设计师的应对：站在设计流程最前端，通过感受真实世界、感受真实的人、捕捉设计情景、丰富细节，去做 AI 做不到的事情"
            }
          ],
          [
            {
              "text": "收尾金句：\"不过于轻视、不过度担忧，随着时代而变，以一定的松弛/弹性去容纳各种可能，也容许自己去做各样的尝试与犯错，就很好。\""
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "五、跨文章主题提炼（创作素材索引）"
      },
      {
        "type": "table",
        "rows": [
          [
            "主题",
            "涉及文章",
            "核心内容",
            "可引用素材"
          ],
          [
            "松弛感 / \"欧洲衡水\"祛魅",
            "文章3（主）、文章1",
            "TUD 不是衡水，是给学生\"松绑\"、鼓励探索；官方有设计师 resilience 研究",
            "C同学开篇、Resilient Designer's Handbook、workshop 制度、改选课模式"
          ],
          [
            "Storytelling 与表达文化",
            "文章1（主）、文章3",
            "荷兰学生表达强；中国学生紧张、不敢说；教育第一层是沟通合作感受",
            "A0海报 vs A4草稿、100个0到1比喻、网球教练视频、晓宁教学法"
          ],
          [
            "\"问为什么\"的教育哲学",
            "文章1（主）",
            "轻呈现重思考；追问问题本质",
            "\"年轻化\"设计案例、教授不问效果图、reflective in/on action"
          ],
          [
            "实践导向 / 研究驱动设计",
            "文章2（主）、文章3",
            "MVP原型、算法模型、用户交互验证；真实企业项目；论文是自然结果",
            "实验室生态、CHI论文15篇、毕业生去向（飞利浦/宝马/宜家/耐克）"
          ],
          [
            "主动探索与 networking",
            "文章3（主）",
            "主动联系老师进实验室、conference 社交、咖啡馆社交",
            "C同学三个案例、每周三 workshop"
          ],
          [
            "AI 时代的设计师价值",
            "文章1、文章3",
            "AI 拉平门槛；真正留下的是思考与判断；AI 无法\"经验世界\"",
            "晓宁三点建议、裁员50%、C同学 AI 观点"
          ],
          [
            "毕业难度与课程强度",
            "文章2（主）",
            "延毕常见、每日记录、课程强度大",
            "zeqi原话、荷兰学生三年毕业现象"
          ],
          [
            "申请要点",
            "文章2、文章3",
            "三大项目差异、GPA75%、作品集规格、动机信写法",
            "项目对比表、作品集评审规则、EIT动机信案例"
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "六、可直接引用的金句清单（按主题归类）"
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "中外学生差异",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "\"他们非常会storytelling。荷兰学生的表达比他们实际做的似乎多十倍。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"作为中国学生，我们正好相反。我们的表达可能只有画图能力的十分之一。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"荷兰同学做了100个从0到1，中国学生做了1个从1到100。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"你做了什么当然重要，但别人更愿意为你创造出来的需求、真正击中痛点的想法买单。\"（晓宁）"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "教育理念",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "\"很多时候，无法很好回答一个问题，是因为没有真正理解问题是什么，却已经开始行动。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"未来教育不应再把重点放在技术侧……第一层永远是教学生如何放大自己作为人的特性：沟通、合作、感受。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"真正留下来的工作，反而越来越像代尔夫特教的那些东西：思考和判断。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"建筑只是一个载体。真正重要的是，它让我学会如何处理复杂问题。\"（晓宁）"
            }
          ],
          [
            {
              "text": "\"行业会有周期，技术不断变化，真正能陪着一个人走下去的，往往不是专业本身，而是背后那套看世界、解决问题的方法。\"（晓宁）"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "排名与定位",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "\"哈佛在定义问题，代尔夫特在解决问题。\"（一只梨）"
            }
          ],
          [
            {
              "text": "\"人机交互，是一门实践学科。\"（一只梨）"
            }
          ],
          [
            {
              "text": "\"看排名，一定要多维度一起看。这不是哈佛被低估，这是两所不同学校，对交互设计教育也有不同的理念。\"（一只梨）"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "就读体验",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "\"TuD毕业确实挺困难的！有很多的国际学生甚至会选择延毕几个月，荷兰本土学生也大多会选择三年去做这个项目，而不是两年。\"（zeqi）"
            }
          ],
          [
            {
              "text": "\"说他（代尔夫特）是欧洲衡水、课很多、同学很卷等等，但我恰恰是来了代尔夫特，学会了松弛。\"（C同学）"
            }
          ],
          [
            {
              "text": "\"Find purpose by embracing the journey, and go beyond your comfort zone.\"（《The Resilient Designer's Handbook》）"
            }
          ],
          [
            {
              "text": "\"它并非是要求学生有多么多么好的成果产出，也不认为一个好的创意是push出来的。\"（C同学）"
            }
          ],
          [
            {
              "text": "\"解决问题的过程：解决问题、提出问题其实是一个不断交织、不断进行的过程。\"（C同学）"
            }
          ]
        ]
      },
      {
        "type": "paragraph",
        "segments": [
          {
            "text": "networking 与 AI",
            "strong": true
          }
        ]
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "\"每个人都有自己的亮点，如果不主动地去展示自己……基本很难被看见。\"（C同学）"
            }
          ],
          [
            {
              "text": "\"AI确实可以做得越来越好，但它没有办法去'经验这个世界'。\"（C同学）"
            }
          ],
          [
            {
              "text": "\"不过于轻视、不过度担忧，随着时代而变，以一定的松弛/弹性去容纳各种可能，也容许自己去做各样的尝试与犯错，就很好。\"（C同学）"
            }
          ]
        ]
      },
      {
        "type": "heading",
        "level": 2,
        "text": "七、建议的文章创作角度（供讨论）"
      },
      {
        "type": "list",
        "items": [
          [
            {
              "text": "祛魅向",
              "strong": true
            },
            {
              "text": "：给 TUD（以及留学焦虑）祛魅——\"欧洲衡水\"的传闻 vs 真实的松弛感，用 C 同学的亲历 + 晓宁的导师观察做双重视角"
            }
          ],
          [
            {
              "text": "教育对比向",
              "strong": true
            },
            {
              "text": "：中外学生差异与代尔夫特\"问为什么\"的教育哲学——A0 海报故事做引子，延伸到教育本质、AI 时代"
            }
          ],
          [
            {
              "text": "申请指南向",
              "strong": true
            },
            {
              "text": "：从 HCI 排名切入，详解三大交互项目差异与申请要求，结合真实案例（田老师、C同学）"
            }
          ],
          [
            {
              "text": "综合体验向",
              "strong": true
            },
            {
              "text": "：一篇完整的 TUD 就读全景——申请、课程、workshop、networking、毕业难度、就业出路"
            }
          ],
          [
            {
              "text": "AI时代设计师向",
              "strong": true
            },
            {
              "text": "：以\"代尔夫特教的东西\"为主线，讨论 AI 时代设计师/学生的核心能力"
            }
          ]
        ]
      }
    ]
  },
  {
    "_id": "article-uw-hci-portfolio",
    "id": "uw-hci-portfolio",
    "category": "作品集",
    "title": "申请交互，作品集到底该放什么",
    "excerpt": "把成品页放进作品集不难。难的是让读的人看见你如何定义问题、怎么取舍，又怎样承认一次判断错了。",
    "readTime": "8 min",
    "date": "2026.08",
    "body": [
      "我作品集里最不想放的一页，是一个失败方案。界面不完整，也没有最后那版好看。我还是放了。",
      "因为那一页比成品更像我做项目时的样子。我们一开始觉得用户需要一个更详细的功能，访谈和测试做完才发现，问题根本不在信息不够，而在用户不知道下一步会发生什么。后来整条流程都改了。",
      "如果只放最终页面，别人看到的是结果。放进那次修改，别人至少能看到我怎么发现自己错了。",
      "申请交互时，作品集不是作品展。它更接近一份带图的工作记录。",
      "我现在会把每个 case 的第一屏当成一道门槛。读的人滑十秒钟，要知道这是给谁做的、当时卡住的是什么、我在里面干了什么。后面才放研究、草图和页面。很多作品集一开头就是完整 UI，我会下意识觉得作者把最困难的那一段藏起来了。漂亮页面留着，别让它们先发言。",
      "我会保留项目最开始的那个问题。不是“我们做了一个帮助用户的产品”，要写清楚谁在什么情境下遇到了什么麻烦，研究怎么改变了判断。",
      "团队项目尤其要写自己的位置。别写“我们调研了”“我们迭代了”，看不出你到底负责什么。你做的是访谈、信息架构、原型，还是那个一直把大家从跑偏的方案里拉回来的人，差别很大。",
      "写角色时我会交代一个动作和一份证据。比如我访谈了谁，问题怎么从二十条收成六条；我把什么信息重排了，测试里哪个人因此少问了一次路；我和工程同学争的到底是什么。没有很大的数据也可以，别把一次测试写成“验证成功”。五个人说不懂，就写五个人说不懂。这个分寸比漂亮的结果更可信。",
      "还有一点。不要把每个项目都讲成成功案例。",
      "研究结论刚好支持方案，测试刚好证明设计有效，最后用户也满意，这种项目太顺了，反而不太像真的。选一个被放弃的判断讲出来就够。",
      "我还会留一页讲取舍。时间不够时，我们先砍掉了哪个功能，为什么；如果隐私、成本或技术限制把原方案卡住，后来怎么绕过去。申请交互的人不需要假装自己什么都会，老师通常能一眼看出。把边界画出来，反倒说明你知道设计不是只画一个理想状态。",
      "作品集当然要好看。排版乱、图看不清，谁也没义务替你找重点。但好看只是让人愿意往下看。真正有用的是，别人看完知道你遇到模糊问题时，怎么开始。",
      "最后是删。项目不够成熟，就缩成两页，别硬撑成十页；一个 case 能讲完的问题，不要再复制三张几乎一样的流程图。作品集不是把努力全部交出去，是让对方愿意约你聊四十分钟。到那时，你有东西可讲，比页数多重要得多。"
    ],
    "images": [
      {
        "after": 3,
        "alt": "HCDE 学生展示研究海报",
        "web": "images/articles/portfolio-poster.jpg",
        "mini": "/images/articles/portfolio-poster.jpg"
      },
      {
        "after": 8,
        "alt": "Capstone 项目演示",
        "web": "images/articles/portfolio-capstone.jpg",
        "mini": "/images/articles/portfolio-capstone.jpg"
      },
      {
        "after": 11,
        "alt": "Poster session 展示",
        "web": "images/articles/portfolio-session.jpg",
        "mini": "/images/articles/portfolio-session.jpg"
      }
    ],
    "status": "published"
  },
  {
    "_id": "article-uw-mhcid-year",
    "id": "uw-mhcid-year",
    "category": "留学体验",
    "title": "一年制 MHCI+D 的 365 天，到底有多忙",
    "excerpt": "一年制最难受的不是哪一周突然爆掉，而是一个项目刚交完，下一个已经开始。忙里真正练的是怎样做暂时判断。",
    "readTime": "8 min",
    "date": "2026.08",
    "body": [
      "开学前有人问我，一年制到底有多忙。我当时说，应该就是作业多一点。第二周就不这么说了。",
      "MHCI+D 是 11 个月的 cohort 项目。时间表会把人推得很快，但“忙”不只是睡得少。最难的部分，是你还没想清楚一个问题，就得拿着它去跟组员、老师和外部的人讨论。对方会问你为什么。你不能总回答“我觉得”。",
      "我后来把一周拆开看，才知道时间去哪了。上课和读材料占掉白天，晚上不是单纯做作业，更多是在约访谈、整理记录、改共享文档、补一个组员没做完的部分。周末原本想留给求职，常常被下周的演示提前拿走。一年制最难受的不是某一周爆掉，是它没有很长的恢复期，刚交完一个东西，下一个已经开始了。",
      "我以前习惯先把方案想完整。至少在自己心里完整，再讲出来。studio 不是这个逻辑。它要求你尽早把半成品放到桌上，让别人挑错。研究没做够，问题定义太大，原型只是在逃避判断，这些都会被人说出来。",
      "刚开始我会把 critique 当成否定。后来才慢慢分开：别人否定的是这个版本，不是我这个人。虽然在凌晨一点的时候，这两件事很难分。",
      "小组作业也很消耗人。有人觉得研究更重要，有人想赶快做出来。项目快结束时，所有人都会有点固执。",
      "我学到一个很笨但有用的习惯：每次会后写三句话，今天到底决定了什么，谁在什么时候交什么，下次争的是哪一个问题。不要只靠大家“应该都记得”。团队做得差的时候，很多矛盾不是意见不同，是每个人脑子里那份项目版本不一样。把它写出来以后，气氛不一定立刻变好，至少不会继续空转。",
      "我后来不太用“抗压”形容这段时间。这个词很方便，也没什么内容。",
      "它更像是训练你在答案不完整、时间不够、意见互相打架的时候，先做一个暂时的判断。然后在新证据出现以后，把它改掉。",
      "如果还想找工作，这个节奏会更别扭。作品集、简历、投递和面试准备不会等课程结束才出现。有人把求职完全挪到最后，风险很高；也有人一开始就把项目当作品集素材，研究记录、失败版本、自己负责的部分都顺手存下来。后者并不轻松，只是毕业前不会突然发现，过去十个月没有一件东西讲得清。",
      "毕业以后，我还会熬夜吗。会。",
      "但我现在知道，熬夜本身不说明任何事。真正有用的是，第二天你能不能解释自己昨晚为什么改了那个决定。"
    ],
    "images": [
      {
        "after": 3,
        "alt": "MHCI+D 的 Capstone demo",
        "web": "images/articles/mhcid-demo.jpg",
        "mini": "/images/articles/mhcid-demo.jpg"
      },
      {
        "after": 5,
        "alt": "小组讨论",
        "web": "images/articles/mhcid-team.jpg",
        "mini": "/images/articles/mhcid-team.jpg"
      },
      {
        "after": 10,
        "alt": "课堂展示",
        "web": "images/articles/mhcid-class.jpg",
        "mini": "/images/articles/mhcid-class.jpg"
      }
    ],
    "status": "published"
  },
  {
    "_id": "article-cmu-mhci-miips-metals-which-one",
    "id": "cmu-mhci-miips-metals-which-one",
    "category": "选校",
    "title": "CMU 的 MHCI、MIIPS、METALS，到底怎么选",
    "excerpt": "三个项目都和人、技术、设计沾边，读出来却不是一回事。把自己想解决的问题放进去，选择会清楚很多。",
    "readTime": "7 min",
    "date": "2026.08",
    "tags": [
      "CMU",
      "MHCI",
      "MIIPS",
      "METALS",
      "选校"
    ],
    "body": [
      "我最近把 CMU 这三个项目放在同一张表里看了很久。名字都带着 HCI、innovation、technology 这些词，申请时很容易一起勾上，觉得总有一个能接住自己。其实它们问的不是同一个问题。你想学什么固然重要，但你愿意为什么问题多熬几个晚上，差别更大。",
      "MHCI 是我会先留给那种想把 HCI 方法本身练扎实的人。用户研究怎么做，交互为什么这样组织，一次测试的反馈到底该改哪里，这些东西不会只停在课本里。它是三学期的项目，后半段有和外部合作方一起做的 capstone。毕业去做产品当然可行，只是项目里反复要求你的，是把研究、设计和协作接起来。",
      "所以我不太建议把 MHCI 当成“我想做产品经理，所以去读个 HCI”的捷径。你当然可以毕业去做产品，但如果你对观察人怎么使用东西、把模糊的抱怨拆成可验证的问题没有耐心，读起来会很别扭。它会不断让你解释判断从哪里来。有人喜欢这种追问，有人会觉得效率太低。两种感觉都正常。",
      "MIIPS 的重心更靠近产品怎么在现实里成立。设计、技术和商业不是三门各学一点的配菜，它更像把这几件事放进同一个项目里逼你处理。上午还在聊用户场景，下午就可能要讨论原型能不能做、成本谁来承担、这件事为什么值得被做出来。很多有工作经验的人会觉得这个语境熟悉，因为真实工作本来就不会把问题按学科分好。",
      "它现在有 9 个月和 16 个月两条路径。我不会把它理解成短版和长版的关系。时间更短，意味着你要带着已经成形的能力进去，几乎立刻开始用；时间更长，给你一些试错和选课空间，也要求你别把那段时间花成缓冲区。MIIPS 适合已经能说清自己要走产品、服务或跨学科创新的人。要是只想补一套 UX 基本功，它未必是最省力的地方。",
      "MIIPS 的风险也很明确，课程和同学都很杂。没有自己的轴，很容易每样都碰到一点，最后只剩下一串好看的项目名。我见过比较清醒的做法，是在入学前就承认自己有一块要补，比如研究、原型、叙事，其他课围着它选。学校给的是一个很大的桌面，桌面上放什么，还是你自己决定。",
      "METALS 则更窄一些，也更不该被当成别的项目的备选。它关心的是人怎么学习，技术怎样介入学习过程，以及教育场景里的产品为什么常常比普通 app 难做。课程把学习科学、设计和技术实现放在一起，入学前对编程和统计也有要求。你如果只想做消费互联网里的界面，没必要因为 CMU 的名字绕来这里。",
      "反过来，如果你确实在意教育、培训、知识工具，或者一直对“用户完成任务”之外的事有兴趣，比如一个人到底学会了没有、系统怎样给反馈才不粗暴，METALS 会给你比较少见的语境。它也有 capstone，但讨论的尺度和 MHCI、MIIPS 不一样。这里的难点往往不是把东西做得顺手，而是先搞明白什么算有效。",
      "选的时候我会逼自己写一句很具体的话：毕业后，我希望别人因为哪种能力来找我。写成“懂设计、懂技术、懂商业”没有用，谁都可以这么写。写成“我能把一段混乱的使用反馈做成研究和设计决策”，MHCI 就开始有意义；写成“我能把一个模糊机会推到可落地的产品方案”，再去看 MIIPS；写成“我能为学习场景设计技术，并判断它有没有真的帮到人”，METALS 才值得认真考虑。",
      "最后看一眼你最不擅长、也最不想逃开的那件事。MHCI 会把方法和证据摆到你面前，MIIPS 会让不同立场的人同时对你的方案提要求，METALS 会要求你对学习这件事保持耐心。项目会把你原来没想清楚的部分放大。学费和时间都是真金白银，申请前把这些写清楚，后面少一点自我安慰。"
    ],
    "status": "published",
    "section": "offer",
    "programIds": [
      "us-004-carnegie-mellon-university-cmu-master-of-human-computer-inte",
      "us-006-carnegie-mellon-university-cmu-master-of-integrated-innovati",
      "us-007-carnegie-mellon-university-cmu-master-of-educational-technol"
    ]
  },
  {
    "_id": "article-cmu-miips-9-or-16-months",
    "id": "cmu-miips-9-or-16-months",
    "category": "选校",
    "title": "MIIPS 的 9 个月和 16 个月，怎么选",
    "excerpt": "这不是短版和长版的区别。选错节奏，后面每一周都会用来补最开始没想过的账。",
    "readTime": "7 min",
    "date": "2026.08",
    "tags": [
      "CMU",
      "MIIPS",
      "选校",
      "留学规划"
    ],
    "body": [
      "拿到 MIIPS offer 以后，9 个月还是 16 个月是最容易被一句话带过去的选择。有人说 16 个月能实习，所以国际生都该选它；有人说 9 个月快，早毕业早上岸。听着都没错，放到具体的人身上，往往就不够用了。",
      "我更愿意把它看成两种进入项目的姿势。9 个月那条路，默认你已经带着一套比较能用的能力进来。可能你做过几年产品，可能作品集已经有真实项目，也可能公司只是希望你回去时多一层跨学科的视角。它的节奏很紧，几乎没有“我先看看自己喜欢什么”的余地。你会一直在用已有的东西，补一点新的判断。",
      "16 个月多出来的，不该只被理解成一段空白的暑假或一行更好看的履历。它给的是一个可以试错的学期和更长的连接时间。对一个设计基础薄、又想把产品方向讲完整的人，这很有用。你可以把一个课程项目继续做下去，找导师聊，去碰不熟悉的选修，再拿着成型一些的材料找机会。前提是你知道自己在补什么。",
      "很多人会说自己“什么都想学”，我听到这句话一般会有点警惕。MIIPS 本来就很杂，设计、工程、商业都要碰。再多几个月，如果没有一个明确缺口，最后很可能只是多上了几门课，多认识了一些人，作品集还是散的。时间不会自动变成能力，甚至会把拖延放大得很体面。",
      "我会先做一个很不浪漫的盘点。现在的作品集里，有没有一个项目能完整说明我怎么从问题走到方案？我有没有一段能在面试里讲清楚的协作经历？毕业后要投的方向，究竟缺的是实习、技术理解，还是产品判断？前两个都很虚，或者每个问题的答案都靠“到学校再说”，我会倾向给自己留更长的跑道。",
      "反过来，已经做过相关工作的人也别因为 16 个月听起来更保险就条件反射地选它。多读一个学期有真实成本，学费、房租、延后全职的机会成本，都不是表格里可以忽略的一格。更重要的是，有些人需要的并不是再补一层学生项目，而是快一点把现有经验重新组织好，带回工作里去。9 个月不等于仓促，前提是入学前已经准备好。",
      "至于实习，别把它理解成 16 个月的赠品。它更像一段需要自己经营的窗口。简历、作品集、想投什么岗位、谁可以帮你校正方向，这些东西在开学前就该有个雏形。没有的话，读到第二学期再临时找，也会很被动。项目提供的是时间和环境，不是替你投递和面试。",
      "官网每年会更新具体的学制和课程安排，最后当然要以当届说明为准。但判断不用等官网替你做：你是要拿现成能力去重新组合，还是确实需要一段时间把自己练成另一个样子。前者可以读得很快，后者别假装自己只需要九个月。"
    ],
    "status": "published",
    "section": "offer",
    "programIds": [
      "us-006-carnegie-mellon-university-cmu-master-of-integrated-innovati"
    ]
  },
  {
    "_id": "article-cmu-miips-portfolio-how-many-projects",
    "id": "cmu-miips-portfolio-how-many-projects",
    "category": "作品集",
    "title": "申请 MIIPS，作品集放几个项目才够",
    "excerpt": "项目数量只是表面问题。真正要看的是，读完以后别人能不能说出你是怎么做判断的。",
    "readTime": "7 min",
    "date": "2026.08",
    "tags": [
      "CMU",
      "MIIPS",
      "作品集",
      "申请"
    ],
    "body": [
      "我不太喜欢“作品集到底放几个项目”这个问题后面那种急切。好像只要得到一个数字，剩下的时间就能照着填满。过去申请者常提 3 到 6 个项目，4 个比较常见。这能当作一个检查范围，不能当成录取公式。三个讲透的项目，通常比六个半成品有说服力。",
      "我见过最可惜的一种作品集，是每个项目都完成得很辛苦，读完却不知道作者想成为什么样的人。做了 app、服务设计、装置、AI 产品，种类很全，页面也漂亮。但所有项目都只停在“发现问题，做出方案”。你看不到这个人最擅长哪一种观察，也看不到他在真实限制里怎么取舍。",
      "有个案例我一直记得。最初的题目是“文字的进化”，视觉材料很多，概念也不差。导师问了一句：这究竟在解决谁的什么问题？它就卡住了。后来作者把它改成关于亚裔移民与文化回避的卡牌交流工具，才开始有真实的人、尴尬的场景和需要被验证的假设。不是说每个项目都要背一个宏大社会议题，而是别把漂亮的形式当成问题本身。",
      "所以我会先选一个能把底牌露出来的项目。它最好有真实约束，可能来自工作、学校合作、某个你真的接触得到的人群。读者需要看见你怎么定义范围，研究以后放弃了什么，方案受什么条件限制。这个项目不需要完美，反而最好留一点没解决的地方。没有边界的 case，通常也没有什么可判断的。",
      "剩下的项目不必为了“多样性”硬凑类别。我不需要你把游戏、硬件、网页、服务设计各摆一个，像在点菜。更有用的组合是，每个项目负责暴露不同的能力。有的项目说明你能做研究和梳理信息，有的说明你能把概念做成可讨论的原型，有的说明你在团队里能推进事情。它们放在一起，应该是一个人，不是四份作业。",
      "团队项目尤其容易写虚。别再用“我们访谈了用户”“我们经过多轮迭代”这种话，读的人没有义务替你还原角色。你访谈了谁，怎么把问题收紧，你和工程或商业同学在哪一步意见不一样，最后谁为了什么妥协，这些都比一整屏成果图值钱。你不负责视觉也没关系，把你真正做的那一段写得够具体。",
      "还有一个很实际的删法：把每个项目压缩成一句话，看它能不能回答“为什么要留在这本作品集里”。如果答案是“它做得很久”或者“页面最好看”，我会先放进候选删除区。项目做得久不等于它适合申请，页面好看只保证对方愿意多滑两下。",
      "最后再回到数量。大多数人做 3 到 4 个足够了，前提是每个都有清楚的角色、证据和一个不太顺的转折。项目还没成熟，就宁愿少放。申请 MIIPS 不是向别人证明你什么都碰过，而是让对方相信，遇到一件还没有答案的事，你知道从哪里开始做。"
    ],
    "status": "published",
    "section": "portfolio",
    "programIds": [
      "us-006-carnegie-mellon-university-cmu-master-of-integrated-innovati"
    ]
  },
  {
    "_id": "article-cmu-non-design-background-application",
    "id": "cmu-non-design-background-application",
    "category": "申请",
    "title": "非设计背景申请 CMU，材料到底怎么讲",
    "excerpt": "非设计背景不是一段需要藏起来的前史。问题在于，你有没有把它诚实地接到现在想做的事上。",
    "readTime": "8 min",
    "date": "2026.08",
    "tags": [
      "CMU",
      "MIIPS",
      "转专业",
      "申请",
      "文书"
    ],
    "body": [
      "非设计背景申请 CMU，最容易做错的不是项目不够多，是太急着把过去切掉。英语、工程、咨询、金融，很多人一开始都想证明自己已经是设计师，于是用几个月赶四个 app，文书里再写一句“我一直热爱用户体验”。这套材料看起来很努力，读完还是会有一个问题：那你原来那些年到底在干什么？",
      "我会先把旧经历摊开，不加 UX 标签。做英语或语言学的人，可能真的研究过语言怎样影响理解；做工程的人，知道一个功能从原型到实现会经过哪些妥协；做咨询的人，见过不同角色如何把同一个问题说成不同版本。它们不是设计能力本身，却都是之后做设计时会用到的观察方式。先把事实写出来，再决定它能连到哪里。",
      "接着找一段真正的转折。不是“我看了一篇文章所以想转行”，而是你在哪个场景里开始承担了新的工作。有人在创业时因为人手不够开始做交互，有人做项目时发现用户根本听不懂团队的表达，有人做技术原型后第一次意识到，能跑和好用是两件事。这个场景要小一点，越具体越好。你当时做了什么，哪里没做好，后来为什么还想继续学。",
      "文书不需要把过去每一段经历都救回来。我会只留两三件能互相照应的事。比如一段工作经历证明你接触过真实限制，一个自发项目证明你已经愿意进入陌生的方法，一次失败说明你不是只会把兴趣说得很漂亮。把这些串起来，读者就能知道你不是突然换了个赛道，而是已经在往这里走。",
      "作品集同理。非设计背景的人不必硬凑成标准 UX 作品集。你可以放技术原型、研究项目、服务流程、实体交互，前提是它们能说清人在哪里、问题在哪里、你的决定改了什么。一个工程背景的项目，别只放架构图；一个语言学项目，也别只放文献。把你怎样接触到使用者、怎样修改了方案放进去，才开始像申请材料。",
      "要补的短板还是得补。视觉层级很乱、不会做低保真原型、访谈没有逻辑，这些不能靠一段漂亮叙事蒙过去。但补短板和伪造身份是两回事。我的做法是选一个最需要补的环节，认真做一遍，再在材料里承认自己还在学什么。比起四个像模板一样的 UI 项目，一个能说清过程和缺口的项目更可信。",
      "面试时也是。不要把“跨专业”说成一场励志叙事。对方如果问你为什么要来，直接说你从旧专业里带来了什么、现在缺什么、这个项目的工作方式为什么能补上。别把学校课程名念一遍。你要让人听见一个已经做过判断的人，而不是一个正在等学校替自己选方向的人。",
      "非设计背景当然会增加准备成本，这句实话没必要绕开。但它也会让你有机会写出不太一样的材料。前提是别忙着变得像别人。把旧背景里真正有用的东西留下，把新能力拿出证据，剩下的交给项目匹配。"
    ],
    "status": "published",
    "section": "writing",
    "programIds": []
  },
  {
    "_id": "article-cmu-miips-first-semester",
    "id": "cmu-miips-first-semester",
    "category": "留学体验",
    "title": "MIIPS 第一学期，到底在学什么",
    "excerpt": "第一学期最强烈的感受，不一定是学得很深，而是你会被迫把设计、技术和商业放进同一张桌子。",
    "readTime": "7 min",
    "date": "2026.08",
    "tags": [
      "CMU",
      "MIIPS",
      "课程",
      "留学体验"
    ],
    "body": [
      "如果你期待 MIIPS 第一学期像选一个方向然后一路钻下去，可能会有点失望。它更像一次高密度的轮转。设计、工程、商业、表达，东西从不同方向压过来。某位毕业生把这种感觉说得很直白：每个领域都碰一下，课程有时显得散。这个评价我觉得挺诚实。",
      "散不一定等于没用，只是它不会替你形成主线。过去的课程记录里，有人通过重新设计急救箱走完整个设计流程，也有人在制造课把面包机拆开，逐个看材料、价格和零件是否真的必要。听上去和做一个 app 很远，但它们都在训练同一件事：不要把方案当成天上掉下来的答案，先看它为什么会长成这样。具体课程和学分会随届次调整，这些场景更值得记住。",
      "商业课带来的麻烦通常更现实。你会发现一个想法就算用户喜欢，也要有人愿意为它付钱、有人能持续维护、团队能解释它为什么值得做。设计学生第一次碰到这些问题，常常觉得它们破坏了创意；工程背景的人则可能更习惯可行性，却不习惯去问用户到底在不在乎。大家都要换一点脑子。",
      "工程部分也有自己的尴尬。基础不够的人会突然意识到，和开发沟通不是学几个名词就够；已经做过工程的人又容易觉得内容太基础。有人会申请 waive，把时间换去上别的课。这不代表谁比较强，只是你得尽早知道自己的短板到底在哪。既然项目本来就短，把时间浪费在已经会的东西上，挺可惜。",
      "我反而觉得第一学期最累的是小组协作。不同背景的人在同一个项目里，连“这个东西做完了”是什么意思都不一样。设计同学想继续打磨体验，工程同学想把范围收住，商业同学已经在问谁来用、怎么卖。吵起来很正常，真正有价值的是你能不能把吵架里那些模糊的分歧说清楚。",
      "所以开学前我会建议先做一件很土的事：给自己定一个主问题。比如我想把用户研究做扎实，或者我想知道技术限制怎样改变设计决策。课程再散，也都可以往这个问题上靠。每上一门课，留一点材料给自己，最后把它们收进同一个项目或作品集叙事里。否则学期结束，很容易只记得自己交了很多 due。",
      "第一学期也别把求职、社交、补技能全塞满。你当然可以做，但要接受有些周会非常乱。MIIPS 不太像把知识按顺序发给你，更像把不同的语言扔到你面前，看你能不能找到翻译它们的方法。刚开始觉得自己什么都不精，是很常见的。",
      "读完这一段，最有用的结果不是变成会设计、会技术、会商业的全能人。那种说法太省事了。更实际的是，你开始知道每个角色在担心什么，也开始知道自己在哪些地方需要别人。这个意识拿去做后面的项目，会比某一门课的分数耐用得多。"
    ],
    "status": "published",
    "section": "program",
    "programIds": [
      "us-006-carnegie-mellon-university-cmu-master-of-integrated-innovati"
    ]
  }
];

window.ARTICLES = [...window.ARTICLES, ...(window.RICH_ARTICLES || []).filter((richArticle) => !window.ARTICLES.some((article) => article.id === richArticle.id))];
